const CONDITIONS=[
  {"i":"CONDITION_FALSE","p":["Scripting","False"]},
  {"i":"COUNTER","p":["Scripting","Counter compared to a value"]},
  {"i":"UNIT_HEALTH","p":["Health","Unit health % compared to a value"]},
  {"i":"FLAG","p":["Scripting","Flag compared to a value"]},
  {"i":"TEAM_STATE_IS","p":["Team","State","Team state is"]},
  {"i":"TEAM_STATE_IS_NOT","p":["Team","State","Team state is not"]},
  {"i":"CONDITION_TRUE","p":["Scripting","True"]},
  {"i":"TIMER_EXPIRED","p":["Scripting","Timer expired"]},
  {"i":"PLAYER_ALL_DESTROYED","p":["Player","Destroyed","All units and buildings destroyed"]},
  {"i":"PLAYER_ALL_BUILDFACILITIES_DESTROYED","p":["Player","Destroyed","All factories destroyed"]},
  {"i":"TEAM_INSIDE_AREA_PARTIALLY","p":["Team","Area","Team has units in an area"]},
  {"i":"NAMED_INSIDE_AREA","p":["Unit","Area","Unit entered area"]},
  {"i":"TEAM_DESTROYED","p":["Team","Destroyed","Team is destroyed"]},
  {"i":"NAMED_DESTROYED","p":["Unit","Destroyed","Unit is destroyed"]},
  {"i":"NAMED_DYING","p":["Unit","Destroyed","Unit is dying"]},
  {"i":"NAMED_TOTALLY_DEAD","p":["Unit","Destroyed","Unit is finished dying"]},
  {"i":"BRIDGE_BROKEN","p":["Bridge","Bridge is broken"]},
  {"i":"BRIDGE_REPAIRED","p":["Bridge","Bridge is repaired"]},
  {"i":"NAMED_NOT_DESTROYED","p":["Unit","Exists","Unit exists and is alive"]},
  {"i":"TEAM_HAS_UNITS","p":["Team","Exists","Team has units"]},
  {"i":"CAMERA_MOVEMENT_FINISHED","p":["Camera","Camera movement finished"]},
  {"i":"NAMED_INSIDE_AREA","p":["Unit","Area","Unit inside an area"]},
  {"i":"NAMED_OUTSIDE_AREA","p":["Unit","Area","Unit outside an area"]},
  {"i":"TEAM_INSIDE_AREA_ENTIRELY","p":["Team","Area","Team completely inside an area"]},
  {"i":"TEAM_OUTSIDE_AREA_ENTIRELY","p":["Team","Area","Team is completely outside an area"]},
  {"i":"NAMED_ATTACKED_BY_OBJECTTYPE","p":["Unit","Attacked","Unit is attacked by a specific unit type"]},
  {"i":"TEAM_ATTACKED_BY_OBJECTTYPE","p":["Team","Attacked","Team is attacked by a specific unit type"]},
  {"i":"NAMED_ATTACKED_BY_PLAYER","p":["Unit","Attacked","Unit has been attacked by a player"]},
  {"i":"TEAM_ATTACKED_BY_PLAYER","p":["Team","Attacked","Team has been attacked by a player"]},
  {"i":"BUILT_BY_PLAYER","p":["Player","Owns","Player has built an object type"]},
  {"i":"NAMED_CREATED","p":["Unit","Exists","Unit has been created"]},
  {"i":"TEAM_CREATED","p":["Team","Exists","Team has been created"]},
  {"i":"PLAYER_HAS_CREDITS","p":["Player","Money","Player has (comparison) to a number of credits"]},
  {"i":"NAMED_DISCOVERED","p":["Player","Discovered","Player has discovered a specific unit"]},
  {"i":"NAMED_BUILDING_IS_EMPTY","p":["Unit","Garrisoned","A specific building is empty"]},
  {"i":"BUILDING_ENTERED_BY_PLAYER","p":["Player","Player has entered a specific building"]},
  {"i":"ENEMY_SIGHTED","p":["Unit","Sighted","Unit has sighted a(n) friendly|neutral|enemy unit belonging to a player"]},
  {"i":"TYPE_SIGHTED","p":["Unit","Sighted","Unit has sighted a type of unit belonging to a player"]},
  {"i":"TEAM_DISCOVERED","p":["Player","Discovered","Player has discovered a team"]},
  {"i":"NAMED_OWNED_BY_PLAYER","p":["Player","Owns","Player owns the specific Unit"]},
  {"i":"TEAM_OWNED_BY_PLAYER","p":["Player","Owns","Player owns a specific team"]},
  {"i":"PLAYER_HAS_N_OR_FEWER_BUILDINGS","p":["Player","Owns","Player currently owns N or fewer buildings"]},
  {"i":"PLAYER_HAS_N_OR_FEWER_FACTION_BUILDINGS","p":["Player","Owns","Player currently owns N or fewer faction buildings"]},
  {"i":"PLAYER_HAS_POWER","p":["Player","Power","Player's base currently has power"]},
  {"i":"PLAYER_HAS_NO_POWER","p":["Player","Power","Player's base currently has no power"]},
  {"i":"NAMED_REACHED_WAYPOINTS_END","p":["Path","Unit has reached the end of a specific waypoint path"]},
  {"i":"TEAM_REACHED_WAYPOINTS_END","p":["Path","Team has reached the end of a specific waypoint path"]},
  {"i":"NAMED_SELECTED","p":["Selected","Unit currently selected"]},
  {"i":"NAMED_ENTERED_AREA","p":["Unit","Area","Unit enters an area"]},
  {"i":"NAMED_EXITED_AREA","p":["Unit","Area","Unit exits an area"]},
  {"i":"TEAM_ENTERED_AREA_ENTIRELY","p":["Team","Area","Team entirely enters an area"]},
  {"i":"TEAM_ENTERED_AREA_PARTIALLY","p":["Team","Area","One unit enters an area"]},
  {"i":"TEAM_EXITED_AREA_ENTIRELY","p":["Team","Area","Team entirely exits an area"]},
  {"i":"TEAM_EXITED_AREA_PARTIALLY","p":["Team","Area","One unit exits an area"]},
  {"i":"MULTIPLAYER_ALLIED_VICTORY","p":["Multiplayer Victory & Defeat","Multiplayer allied victory"]},
  {"i":"MULTIPLAYER_ALLIED_DEFEAT","p":["Multiplayer Victory & Defeat","Multiplayer allied defeat"]},
  {"i":"MULTIPLAYER_PLAYER_DEFEAT","p":["Multiplayer Victory & Defeat","Multiplayer local player defeat check"]},
  {"i":"HAS_FINISHED_VIDEO","p":["Multimedia","Finished","(UNUSED)Video has completed playing"]},
  {"i":"HAS_FINISHED_SPEECH","p":["Multimedia","Finished","Speech has completed playing"]},
  {"i":"HAS_FINISHED_AUDIO","p":["Multimedia","Finished","Sound has completed playing"]},
  {"i":"PLAYER_TRIGGERED_SPECIAL_POWER","p":["Player","Special Power","Player starts using a special power"]},
  {"i":"PLAYER_COMPLETED_SPECIAL_POWER","p":["Player","Special Power","Player completed using a special power"]},
  {"i":"PLAYER_ACQUIRED_SCIENCE","p":["Player","Science","Player acquired a Science"]},
  {"i":"NAMED_HAS_FREE_CONTAINER_SLOTS","p":["Unit","Container","Container has free container slots"]},
  {"i":"PLAYER_BUILT_UPGRADE","p":["Player","Upgrades","Player built an upgrade"]},
  {"i":"PLAYER_DESTROYED_N_BUILDINGS_PLAYER","p":["Player","Destroyed","Player destroyed N or more of an opponent's buildings"]},
  {"i":"PLAYER_HAS_OBJECT_COMPARISON","p":["Player","Owns","Player has (comparison) unit type"]},
  {"i":"PLAYER_HAS_COMPARISON_UNIT_TYPE_IN_TRIGGER_AREA","p":["Player","Area","Player has (comparison) unit type in an area"]},
  {"i":"PLAYER_HAS_COMPARISON_UNIT_KIND_IN_TRIGGER_AREA","p":["Player","Owns","Player has (comparison) kind of unit or structure in an area"]},
  {"i":"PLAYER_POWER_COMPARE_PERCENT","p":["Player","Power","Player has (comparison) percent power supply to consumption"]},
  {"i":"PLAYER_EXCESS_POWER_COMPARE_VALUE","p":["Player","Power","Player has (comparison) kilowatts excess power supply"]},
  {"i":"UNIT_EMPTIED","p":["Unit","Container","Container has emptied its contents"]},
  {"i":"SKIRMISH_SPECIAL_POWER_READY","p":["Player","Special Power","Player's special power is ready to fire"]},
  {"i":"UNIT_HAS_OBJECT_STATUS","p":["Status","Unit","Unit has object status"]},
  {"i":"TEAM_SOME_HAVE_OBJECT_STATUS","p":["Status","Team","Team has object status - partial"]},
  {"i":"SKIRMISH_VALUE_IN_AREA","p":["Player","Area","Player has total value in area"]},
  {"i":"SKIRMISH_PLAYER_FACTION","p":["Skirmish","Player","Player is faction"]},
  {"i":"SKIRMISH_SUPPLIES_VALUE_WITHIN_DISTANCE","p":["Skirmish Only","Supplies are within specified distance"]},
  {"i":"SKIRMISH_TECH_BUILDING_WITHIN_DISTANCE","p":["Skirmish Only","Tech building is within specified distance"]},
  {"i":"SKIRMISH_UNOWNED_FACTION_UNIT_EXISTS","p":["Skirmish","Unowned faction unit -- comparison"]},
  {"i":"SKIRMISH_PLAYER_HAS_COMPARISON_GARRISONED","p":["Skirmish","Player","Player has garrisoned buildings -- comparison"]},
  {"i":"SKIRMISH_PLAYER_HAS_UNITS_IN_AREA","p":["Player","Area","Player has units in an area"]},
  {"i":"SKIRMISH_PLAYER_HAS_BEEN_ATTACKED_BY_PLAYER","p":["Player","Player has been attacked by player"]},
  {"i":"SKIRMISH_PLAYER_IS_OUTSIDE_AREA","p":["Player","Area","Player doesn't have units in an area"]},
  {"i":"MUSIC_TRACK_HAS_COMPLETED","p":["Multimedia","Finished","Music track has completed some number of times"]},
  {"i":"SUPPLY_SOURCE_SAFE","p":["Skirmish","Supply Source","Supply source is safe"]},
  {"i":"SUPPLY_SOURCE_ATTACKED","p":["Skirmish","Supply Source","Supply source is attacked"]},
  {"i":"START_POSITION_IS","p":["Skirmish","Start position"]},
  {"i":"PLAYER_LOST_OBJECT_TYPE","p":["Player","Destroyed","Player has lost an object of type"]}
];
const ACTIONS=[
  {"i":"DEBUG_MESSAGE_BOX","p":["Scripting","Debug","Display message and pause"]},
  {"i":"DEBUG_STRING","p":["Scripting","Debug","Display string"]},
  {"i":"DEBUG_CRASH_BOX","p":["Scripting","Debug","Display a crash box (debug and internal builds only)"]},
  {"i":"SET_FLAG","p":["Scripting","Flags","Set flag to value"]},
  {"i":"SET_COUNTER","p":["Scripting","Counters","Set counter to a value"]},
  {"i":"SET_INFANTRY_LIGHTING_OVERRIDE","p":["Map","Environment","Infantry Lighting - Set"]},
  {"i":"RESET_INFANTRY_LIGHTING_OVERRIDE","p":["Map","Environment","Infantry Lighting - Reset"]},
  {"i":"VICTORY","p":["User","Announce win"]},
  {"i":"DEFEAT","p":["User","Announce lose"]},
  {"i":"NO_OP","p":["Scripting","Debug","Null operation"]},
  {"i":"SET_TIMER","p":["Scripting","Timer","Frame countdown timer -- set"]},
  {"i":"SET_RANDOM_TIMER","p":["Scripting","Timer","Frame countdown timer -- set random"]},
  {"i":"STOP_TIMER","p":["Scripting","Timer","Timer -- stop"]},
  {"i":"RESTART_TIMER","p":["Scripting","Timer","Timer -- restart stopped"]},
  {"i":"PLAY_SOUND_EFFECT","p":["Multimedia","Sound Effect","Play sound effect"]},
  {"i":"ENABLE_SCRIPT","p":["Scripting","Script","Enable Script"]},
  {"i":"DISABLE_SCRIPT","p":["Scripting","Script","Disable script"]},
  {"i":"CALL_SUBROUTINE","p":["Scripting","Script","Run subroutine script"]},
  {"i":"PLAY_SOUND_EFFECT_AT","p":["Multimedia","Sound Effect","Play sound effect at waypoint"]},
  {"i":"DAMAGE_MEMBERS_OF_TEAM","p":["Team","Damage or Remove","Damage the members of a team"]},
  {"i":"MOVE_TEAM_TO","p":["Team","Move","Set to move to a location"]},
  {"i":"TEAM_FOLLOW_WAYPOINTS","p":["Team","Move","Set to follow a waypoint path"]},
  {"i":"TEAM_FOLLOW_WAYPOINTS_EXACT","p":["Team","Move","Set to EXACTLY follow a waypoint path"]},
  {"i":"TEAM_WANDER_IN_PLACE","p":["Team","Move","Set to wander around current location"]},
  {"i":"TEAM_INCREASE_PRIORITY","p":["Team","AI","Increase priority by Success Priority Increase amount"]},
  {"i":"TEAM_DECREASE_PRIORITY","p":["Team","AI","Reduce priority by Failure Priority Decrease amount"]},
  {"i":"TEAM_WANDER","p":["Team","Move","Set to follow a waypoint path -- wander"]},
  {"i":"TEAM_PANIC","p":["Team","Move","Set to follow a waypoint path -- panic"]},
  {"i":"MOVE_NAMED_UNIT_TO","p":["Unit","Move","Move a specific unit to a location"]},
  {"i":"TEAM_SET_STATE","p":["Scripting","Misc","Team custom state - set state"]},
  {"i":"CREATE_REINFORCEMENT_TEAM","p":["Team","Create","Spawn a reinforcement team"]},
  {"i":"SKIRMISH_BUILD_BUILDING","p":["Skirmish Only","Build","Build a building"]},
  {"i":"AI_PLAYER_BUILD_SUPPLY_CENTER","p":["Player","AI","AI player build near a supply source"]},
  {"i":"AI_PLAYER_BUILD_TYPE_NEAREST_TEAM","p":["Player","AI","AI player build nearest specified team"]},
  {"i":"TEAM_GUARD_SUPPLY_CENTER","p":["Team","Guard","Set to guard a supply source"]},
  {"i":"AI_PLAYER_BUILD_UPGRADE","p":["Player","AI","AI player build an upgrade"]},
  {"i":"SKIRMISH_FOLLOW_APPROACH_PATH","p":["Skirmish Only","Move","Team follow approach path"]},
  {"i":"SKIRMISH_MOVE_TO_APPROACH_PATH","p":["Skirmish Only","Move","Team move to approach path"]},
  {"i":"SKIRMISH_BUILD_BASE_DEFENSE_FRONT","p":["Skirmish Only","Build","Build base defense on front perimeter"]},
  {"i":"SKIRMISH_BUILD_BASE_DEFENSE_FLANK","p":["Skirmish Only","Build","Build base defense on flank perimeter"]},
  {"i":"SKIRMISH_BUILD_STRUCTURE_FRONT","p":["Skirmish Only","Build","Build structure on front perimeter"]},
  {"i":"SKIRMISH_BUILD_STRUCTURE_FLANK","p":["Skirmish Only","Build","Build structure on flank perimeter"]},
  {"i":"RECRUIT_TEAM","p":["Team","Create","Recruit a team"]},
  {"i":"MOVE_CAMERA_TO","p":["Camera","Move","Move the camera to a location"]},
  {"i":"ZOOM_CAMERA","p":["Camera","Adjust","Change the camera zoom"]},
  {"i":"CAMERA_FADE_ADD","p":["Camera","Camera FX","Fade using an add blend to white"]},
  {"i":"CAMERA_FADE_SUBTRACT","p":["Camera","Camera FX","Fade using a subtractive blend to black"]},
  {"i":"CAMERA_FADE_MULTIPLY","p":["Camera","Camera FX","Fade using a multiply blend to black"]},
  {"i":"CAMERA_FADE_SATURATE","p":["Camera","Camera FX","Fade using a saturate blend"]},
  {"i":"PITCH_CAMERA","p":["Camera","Adjust","Change the camera pitch"]},
  {"i":"CAMERA_FOLLOW_NAMED","p":["Camera","Follow","Start following a specific unit"]},
  {"i":"CAMERA_STOP_FOLLOW","p":["Camera","Follow","Stop following any units"]},
  {"i":"SETUP_CAMERA","p":["Camera","Adjust","Set up the camera"]},
  {"i":"INCREMENT_COUNTER","p":["Scripting","Counters","Increment counter"]},
  {"i":"DECREMENT_COUNTER","p":["Scripting","Counters","Decrement counter"]},
  {"i":"MOVE_CAMERA_ALONG_WAYPOINT_PATH","p":["Camera","Move","Move along a waypoint path"]},
  {"i":"ROTATE_CAMERA","p":["Camera","Rotate","Rotate around the current viewpoint"]},
  {"i":"RESET_CAMERA","p":["Camera","Move","Reset to the default view"]},
  {"i":"SET_MILLISECOND_TIMER","p":["Scripting","Timer","Seconds countdown timer -- set"]},
  {"i":"SET_RANDOM_MSEC_TIMER","p":["Scripting","Timer","Seconds countdown timer -- set random"]},
  {"i":"ADD_TO_MSEC_TIMER","p":["Scripting","Timer","Seconds countdown timer -- add seconds"]},
  {"i":"SUB_FROM_MSEC_TIMER","p":["Scripting","Timer","Seconds countdown timer -- subtract seconds"]},
  {"i":"CAMERA_MOD_FREEZE_TIME","p":["Camera","Move","Modify","Freeze time during the camera movement"]},
  {"i":"SUSPEND_BACKGROUND_SOUNDS","p":["Multimedia","All Sounds","Suspend all sounds"]},
  {"i":"RESUME_BACKGROUND_SOUNDS","p":["Multimedia","All Sounds","Resume all sounds"]},
  {"i":"CAMERA_MOD_SET_FINAL_ZOOM","p":["Camera","Move","Modify","Set Final zoom for camera movement"]},
  {"i":"CAMERA_MOD_SET_FINAL_PITCH","p":["Camera","Move","Modify","Set Final pitch for camera movement"]},
  {"i":"CAMERA_MOD_LOOK_TOWARD","p":["Camera","Modify","Move","Camera look toward point while moving"]},
  {"i":"CREATE_OBJECT","p":["Unit","Spawn","Spawn unit"]},
  {"i":"TEAM_ATTACK_TEAM","p":["Team","Attack","Set to attack -- another team"]},
  {"i":"NAMED_ATTACK_NAMED","p":["Unit","Attack","Set unit to attack another unit"]},
  {"i":"CREATE_NAMED_ON_TEAM_AT_WAYPOINT","p":["Unit","Spawn","Spawn -- named unit on a team at a waypoint"]},
  {"i":"CREATE_UNNAMED_ON_TEAM_AT_WAYPOINT","p":["Unit","Spawn","Spawn -- unnamed unit on a team at a waypoint"]},
  {"i":"NAMED_APPLY_ATTACK_PRIORITY_SET","p":["AttackPrioritySet","ApplySet","Apply unit's attack priority set"]},
  {"i":"TEAM_APPLY_ATTACK_PRIORITY_SET","p":["AttackPrioritySet","ApplySet","Apply a team's attack priority set"]},
  {"i":"SET_ATTACK_PRIORITY_THING","p":["AttackPrioritySet","CreateSet","Modify a set's priority for a single unit type"]},
  {"i":"SET_ATTACK_PRIORITY_KIND_OF","p":["AttackPrioritySet","CreateSet","Modify a set's priorities for all of a kind"]},
  {"i":"SET_DEFAULT_ATTACK_PRIORITY","p":["AttackPrioritySet","CreateSet","Specify the set's default priority"]},
  {"i":"PLAYER_ADD_RANKLEVEL","p":["Player","Experience","Add or Subtract Rank Levels"]},
  {"i":"PLAYER_SET_RANKLEVEL","p":["Player","Experience","Set Rank Level"]},
  {"i":"PLAYER_SET_RANKLEVELLIMIT","p":["Map","Experience","Set Rank Level Limit for current Map"]},
  {"i":"PLAYER_GRANT_SCIENCE","p":["Player","Science","Grant a Science to a given Player (ignoring prerequisites)"]},
  {"i":"PLAYER_SCIENCE_AVAILABILITY","p":["Player","Science","Set science availability"]},
  {"i":"SET_BASE_CONSTRUCTION_SPEED","p":["Player","AI","Set the delay between building AI teams"]},
  {"i":"NAMED_SET_ATTITUDE","p":["Unit","Mood","Set the general attitude of a specific unit"]},
  {"i":"TEAM_SET_ATTITUDE","p":["Team","Mood","Set the general attitude of a team"]},
  {"i":"NAMED_SET_REPULSOR","p":["Unit","Internal","Repulsor","Set the REPULSOR flag of a specific unit"]},
  {"i":"TEAM_SET_REPULSOR","p":["Team","Internal","Repulsor","Set the REPULSOR flag of a team"]},
  {"i":"NAMED_ATTACK_AREA","p":["Unit","Attack","Set a specific unit to attack a specific trigger area"]},
  {"i":"NAMED_ATTACK_TEAM","p":["Unit","Attack","Set a specific unit to attack a team"]},
  {"i":"TEAM_ATTACK_AREA","p":["Team","Attack","Set to attack -- trigger area"]},
  {"i":"TEAM_ATTACK_NAMED","p":["Team","Attack","Set to attack -- specific unit"]},
  {"i":"TEAM_LOAD_TRANSPORTS","p":["Team","Transport","Transport -- automatically load"]},
  {"i":"NAMED_ENTER_NAMED","p":["Unit","Transport","Transport -- load unit into specific"]},
  {"i":"TEAM_ENTER_NAMED","p":["Team","Transport","Transport -- load team into specific"]},
  {"i":"NAMED_EXIT_ALL","p":["Unit","Transport","Transport -- unload units from specific"]},
  {"i":"TEAM_EXIT_ALL","p":["Team","Transport","Transport -- unload team from all"]},
  {"i":"NAMED_FOLLOW_WAYPOINTS","p":["Unit","Move","Set a specific unit to follow a waypoint path"]},
  {"i":"NAMED_FOLLOW_WAYPOINTS_EXACT","p":["Unit","Move","Set a specific unit to EXACTLY follow a waypoint path"]},
  {"i":"NAMED_GUARD","p":["Unit","Move","Set to guard"]},
  {"i":"TEAM_GUARD","p":["Team","Guard","Set to guard -- current location"]},
  {"i":"TEAM_GUARD_POSITION","p":["Team","Guard","Set to guard -- location"]},
  {"i":"TEAM_GUARD_OBJECT","p":["Team","Guard","Set to guard -- specific unit"]},
  {"i":"TEAM_GUARD_AREA","p":["Team","Guard","Set to guard -- area"]},
  {"i":"NAMED_HUNT","p":["Unit","Hunt","Set a specific unit to hunt"]},
  {"i":"TEAM_HUNT_WITH_COMMAND_BUTTON","p":["Team","Hunt","Set to hunt using commandbutton ability"]},
  {"i":"TEAM_HUNT","p":["Team","Hunt","Set to hunt"]},
  {"i":"PLAYER_HUNT","p":["Player","Hunt","Set all of a player's units to hunt"]},
  {"i":"PLAYER_SELL_EVERYTHING","p":["Player","Set","Set a player to sell everything"]},
  {"i":"PLAYER_DISABLE_BASE_CONSTRUCTION","p":["Player","Build","Set a player to be unable to build buildings"]},
  {"i":"PLAYER_DISABLE_UNIT_CONSTRUCTION","p":["Player","Build","Set a player to be unable to build units"]},
  {"i":"PLAYER_ENABLE_BASE_CONSTRUCTION","p":["Player","Build","Set a player to be able to build buildings"]},
  {"i":"PLAYER_ENABLE_UNIT_CONSTRUCTION","p":["Player","Build","Set a player to be able to build units"]},
  {"i":"OVERSIZE_TERRAIN","p":["Camera","Terrain","Oversize the terrain"]},
  {"i":"BUILD_TEAM","p":["Team","AI","Start building a team"]},
  {"i":"NAMED_DAMAGE","p":["Unit","Damage","Deal damage to a specific unit"]},
  {"i":"NAMED_DELETE","p":["Unit","Damage or Remove","Delete a specific unit"]},
  {"i":"TEAM_DELETE","p":["Team","Damage or Remove","Delete a team"]},
  {"i":"TEAM_DELETE_LIVING","p":["Team","Damage or Remove","Delete a team, but ignore dead guys"]},
  {"i":"NAMED_KILL","p":["Unit","Damage or Remove","Kill a specific unit"]},
  {"i":"TEAM_KILL","p":["Team","Damage or Remove","Kill an entire team"]},
  {"i":"PLAYER_KILL","p":["Player","Damage or Remove","Kill a player"]},
  {"i":"CAMEO_FLASH","p":["User","Flash","Flash a cameo for a specified amount of time"]},
  {"i":"NAMED_FLASH","p":["User","Flash","Flash a specific unit for a specified amount of time"]},
  {"i":"TEAM_FLASH","p":["User","Flash","Flash a team for a specified amount of time"]},
  {"i":"NAMED_CUSTOM_COLOR","p":["User","Flash","Set a specific unit to use a special indicator color"]},
  {"i":"NAMED_FLASH_WHITE","p":["User","Flash","Flash a specific unit white for a specified amount of time"]},
  {"i":"INGAME_POPUP_MESSAGE","p":["User","String","Display Popup Message Box"]},
  {"i":"SOUND_PLAY_NAMED","p":["Multimedia","Sound Effect","Play a sound as though coming from a specific unit"]},
  {"i":"SPEECH_PLAY","p":["Multimedia","Sound Effect","Play a speech file"]},
  {"i":"PLAYER_TRANSFER_OWNERSHIP_PLAYER","p":["Player","Transfer","Transfer assets from one player to another player"]},
  {"i":"NAMED_TRANSFER_OWNERSHIP_PLAYER","p":["Player","Transfer","Transfer a specific unit to the control of a player"]},
  {"i":"PLAYER_EXCLUDE_FROM_SCORE_SCREEN","p":["Player","Score","Exclude this player from the score screen"]},
  {"i":"ENABLE_SCORING","p":["Player","Score","Turn on scoring"]},
  {"i":"DISABLE_SCORING","p":["Player","Score","Turn off scoring"]},
  {"i":"PLAYER_RELATES_PLAYER","p":["Player","Alliances","Change how a player relates to another player"]},
  {"i":"RADAR_CREATE_EVENT","p":["Radar","Create Event","Create a radar event at a specified location"]},
  {"i":"OBJECT_CREATE_RADAR_EVENT","p":["Radar","Create Event","Create  a radar event at a specific object"]},
  {"i":"TEAM_CREATE_RADAR_EVENT","p":["Radar","Create Event","Create  a radar event at a specific team"]},
  {"i":"RADAR_ENABLE","p":["Radar","Control","Enable the radar"]},
  {"i":"NAMED_SET_STEALTH_ENABLED","p":["Unit","Status","Stealth set enabled or disabled"]},
  {"i":"TEAM_SET_STEALTH_ENABLED","p":["Team","Status","Stealth set enabled or disabled"]},
  {"i":"NAMED_SET_UNMANNED_STATUS","p":["Unit","Status","Make unmanned"]},
  {"i":"TEAM_SET_UNMANNED_STATUS","p":["Team","Status","Make unmanned"]},
  {"i":"NAMED_SET_BOOBYTRAPPED","p":["Unit","Status","Make boobytrapped"]},
  {"i":"TEAM_SET_BOOBYTRAPPED","p":["Team","Status","Make boobytrapped"]},
  {"i":"MAP_REVEAL_AT_WAYPOINT","p":["Map","Shroud or Reveal","Reveal map at waypoint -- fog"]},
  {"i":"MAP_SHROUD_AT_WAYPOINT","p":["Map","Shroud or Reveal","Shroud map at waypoint -- add fog"]},
  {"i":"MAP_REVEAL_ALL","p":["Map","Shroud or Reveal","Reveal the entire map for a player"]},
  {"i":"MAP_REVEAL_ALL_PERM","p":["Map","Shroud or Reveal","Reveal the entire map permanently for a player"]},
  {"i":"MAP_REVEAL_ALL_UNDO_PERM","p":["Map","Shroud or Reveal","Un-Reveal the entire map permanently for a player"]},
  {"i":"MAP_SHROUD_ALL","p":["Map","Shroud or Reveal","Shroud the entire map for a player"]},
  {"i":"DISABLE_BORDER_SHROUD","p":["Map","Shroud or Reveal","Border Shroud is turned off"]},
  {"i":"ENABLE_BORDER_SHROUD","p":["Map","Shroud or Reveal","Border Shroud is turned on"]},
  {"i":"TEAM_GARRISON_SPECIFIC_BUILDING","p":["Team","Garrison","Garrison a specific building with a team"]},
  {"i":"EXIT_SPECIFIC_BUILDING","p":["Unit","Garrison","Empty a specific building"]},
  {"i":"TEAM_GARRISON_NEAREST_BUILDING","p":["Team","Garrison","Garrison a nearby building with a team"]},
  {"i":"TEAM_EXIT_ALL_BUILDINGS","p":["Team","Garrison","Exit all buildings a team is in"]},
  {"i":"NAMED_GARRISON_SPECIFIC_BUILDING","p":["Unit","Garrison","Garrison a specific building with a specific unit"]},
  {"i":"NAMED_GARRISON_NEAREST_BUILDING","p":["Unit","Garrison","Garrison a nearby building with a specific unit"]},
  {"i":"NAMED_EXIT_BUILDING","p":["Unit","Garrison","Exit the building the unit is in"]},
  {"i":"PLAYER_EXIT_ALL_BUILDINGS","p":["Player","Garrison","All units leave their garrisons"]},
  {"i":"TEAM_AVAILABLE_FOR_RECRUITMENT","p":["Team","AI","Set whether members of a team can be recruited into another team"]},
  {"i":"TEAM_MERGE_INTO_TEAM","p":["Team","Merge","Merge a team into another team"]},
  {"i":"IDLE_ALL_UNITS","p":["Scripting","Idle or Restart","Idle all units for all players"]},
  {"i":"DISABLE_INPUT","p":["User","Input","User input -- disable"]},
  {"i":"ENABLE_INPUT","p":["User","Input","User input -- enable"]},
  {"i":"SOUND_AMBIENT_PAUSE","p":["Multimedia","SoundEffects","Pause the ambient sounds"]},
  {"i":"SOUND_AMBIENT_RESUME","p":["Multimedia","SoundEffects","Resume the ambient sounds"]},
  {"i":"ENABLE_OBJECT_SOUND","p":["Multimedia","Sound Effect","Enable object's ambient sound"]},
  {"i":"DISABLE_OBJECT_SOUND","p":["Multimedia","Sound Effect","Disable object's ambient sound"]},
  {"i":"MUSIC_SET_TRACK","p":["Multimedia","Music","Play a music track"]},
  {"i":"CAMERA_LETTERBOX_BEGIN","p":["Camera","Letterbox","Begin letterbox mode"]},
  {"i":"CAMERA_LETTERBOX_END","p":["Camera","Letterbox","End letterbox mode"]},
  {"i":"CAMERA_BW_MODE_BEGIN","p":["Camera","Camera FX","Start black & white mode"]},
  {"i":"CAMERA_BW_MODE_END","p":["Camera","Camera FX","Stop black & white mode"]},
  {"i":"CAMERA_MOTION_BLUR_JUMP","p":["Camera","Camera FX","Motion blur zoom with jump cut"]},
  {"i":"DRAW_SKYBOX_BEGIN","p":["Camera","Skybox","Start skybox mode"]},
  {"i":"DRAW_SKYBOX_END","p":["Camera","Skybox","Stop skybox mode"]},
  {"i":"FREEZE_TIME","p":["Scripting","Time","Freeze time"]},
  {"i":"UNFREEZE_TIME","p":["Scripting","Time","Unfreeze time"]},
  {"i":"SHOW_MILITARY_CAPTION","p":["Scripting","Briefing","Show military briefing caption"]},
  {"i":"NAMED_SET_HELD","p":["Unit","Move","Set unit to be held in place, ignoring Physics, Locomotors, etc"]},
  {"i":"NAMED_SET_STOPPING_DISTANCE","p":["Unit","Move","Set stopping distance for current locomotor"]},
  {"i":"SET_STOPPING_DISTANCE","p":["Team","Move","Set stopping distance for each unit's current locomotor"]},
  {"i":"SET_FPS_LIMIT","p":["Scripting","Set max frames per second"]},
  {"i":"DISABLE_SPECIAL_POWER_DISPLAY","p":["Scripting","Special power countdown display -- disable"]},
  {"i":"ENABLE_SPECIAL_POWER_DISPLAY","p":["Scripting","Special power countdown display -- enable"]},
  {"i":"NAMED_HIDE_SPECIAL_POWER_DISPLAY","p":["Unit","Special Power","Special power countdown timer -- hide"]},
  {"i":"NAMED_SHOW_SPECIAL_POWER_DISPLAY","p":["Unit","Special Power","Special power countdown timer -- display"]},
  {"i":"MUSIC_SET_VOLUME","p":["Multimedia","Set the current music volume"]},
  {"i":"TEAM_TRANSFER_TO_PLAYER","p":["Team","Transfer control of a team to a player"]},
  {"i":"PLAYER_SET_MONEY","p":["Player","Set","Set player's money"]},
  {"i":"PLAYER_GIVE_MONEY","p":["Player","Set","Gives or takes from player's money"]},
  {"i":"DISPLAY_COUNTER","p":["Scripting","Counters","Display an individual counter to the user"]},
  {"i":"HIDE_COUNTER","p":["Scripting","Counters","Hide an individual counter from the user"]},
  {"i":"DISPLAY_COUNTDOWN_TIMER","p":["Scripting","Timer","Display an individual timer to the user"]},
  {"i":"HIDE_COUNTDOWN_TIMER","p":["Scripting","Timer","Hides an individual timer from the user"]},
  {"i":"DISABLE_COUNTDOWN_TIMER_DISPLAY","p":["Scripting","Timer","Hide all timers from the user"]},
  {"i":"NAMED_STOP_SPECIAL_POWER_COUNTDOWN","p":["Unit","Special power","Countdown timer -- pause"]},
  {"i":"NAMED_START_SPECIAL_POWER_COUNTDOWN","p":["Unit","Special power","Countdown timer -- resume"]},
  {"i":"NAMED_SET_SPECIAL_POWER_COUNTDOWN","p":["Unit","Special power","Countdown timer -- set"]},
  {"i":"SKIRMISH_FIRE_SPECIAL_POWER_AT_MOST_COST","p":["Player","Special power","Special power -- fire at enemy's highest cost area"]},
  {"i":"PLAYER_REPAIR_NAMED_STRUCTURE","p":["Player","Repair named bridge or structure"]},
  {"i":"NAMED_FIRE_SPECIAL_POWER_AT_WAYPOINT","p":["Unit","Special power","Special Power -- fire at location"]},
  {"i":"REFRESH_RADAR","p":["Radar","Refresh radar terrain"]},
  {"i":"NAMED_STOP","p":["Unit","Set a specific unit to stop"]},
  {"i":"TEAM_STOP","p":["Team","Stop","Have team stop"]},
  {"i":"TEAM_STOP_AND_DISBAND","p":["Team","Stop","Have team stop, then disband"]},
  {"i":"TEAM_SET_OVERRIDE_RELATION_TO_TEAM","p":["Team","Alliance","Override a team's relationship to another team"]},
  {"i":"TEAM_REMOVE_OVERRIDE_RELATION_TO_TEAM","p":["Team","Alliance","Remove an override to a team's relationship to another team"]},
  {"i":"TEAM_REMOVE_ALL_OVERRIDE_RELATIONS","p":["Team","Alliance","Remove all overrides to team's relationship to teams and","or players"]},
  {"i":"CAMERA_TETHER_NAMED","p":["Camera","Follow","Begin tether camera to a specific unit"]},
  {"i":"CAMERA_STOP_TETHER_NAMED","p":["Camera","Follow","End tether to any units"]},
  {"i":"CAMERA_LOOK_TOWARD_OBJECT","p":["Camera","Rotate","Rotate toward unit"]},
  {"i":"CAMERA_LOOK_TOWARD_WAYPOINT","p":["Camera","Rotate","Rotate to look at a waypoint"]},
  {"i":"UNIT_DESTROY_ALL_CONTAINED","p":["Unit","Damage or Remove","Kill all units contained within a specific transport or structure"]},
  {"i":"TEAM_SET_OVERRIDE_RELATION_TO_PLAYER","p":["Team","Override a team's relationship to another player"]},
  {"i":"PLAYER_SET_OVERRIDE_RELATION_TO_TEAM","p":["Player","Alliances","Override a player's relationship to another team"]},
  {"i":"TEAM_EXECUTE_SEQUENTIAL_SCRIPT","p":["Team","SequentialScript","Execute script sequentially -- start"]},
  {"i":"TEAM_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING","p":["Team","SequentialScript","Execute script sequentially -- looping"]},
  {"i":"TEAM_STOP_SEQUENTIAL_SCRIPT","p":["Team","SequentialScript","Execute script sequentially -- stop"]},
  {"i":"UNIT_IDLE_FOR_FRAMECOUNT","p":["Unit","Set to idle for some number of frames"]},
  {"i":"TEAM_GUARD_FOR_FRAMECOUNT","p":["Team","SequentialScript","Set to guard -- number of frames"]},
  {"i":"TEAM_IDLE_FOR_FRAMECOUNT","p":["Team","SequentialScript","Set to idle for some number of frames"]},
  {"i":"WATER_CHANGE_HEIGHT","p":["Map","Modify","Adjust water height to a new level"]},
  {"i":"WATER_CHANGE_HEIGHT_OVER_TIME","p":["Map","Modify","Adjust water height to a new level with damage over time"]},
  {"i":"NAMED_USE_COMMANDBUTTON_ABILITY","p":["Unit","CommandButton","Use commandbutton ability"]},
  {"i":"NAMED_USE_COMMANDBUTTON_ABILITY_ON_NAMED","p":["Unit","CommandButton","Use commandbutton ability on an object"]},
  {"i":"NAMED_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT","p":["Unit","CommandButton","Use commandbutton ability at a waypoint"]},
  {"i":"NAMED_USE_COMMANDBUTTON_ABILITY_USING_WAYPOINT_PATH","p":["Unit","CommandButton","Use commandbutton ability following waypoint path"]},
  {"i":"TEAM_USE_COMMANDBUTTON_ABILITY","p":["Team","CommandButton","Use commandbutton ability"]},
  {"i":"TEAM_USE_COMMANDBUTTON_ABILITY_ON_NAMED","p":["Team","CommandButton","Use commandbutton ability on an object"]},
  {"i":"TEAM_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT","p":["Team","CommandButton","Use commandbutton ability at a waypoint"]},
  {"i":"MAP_SWITCH_BORDER","p":["Map","Modify","Change the active area of the map"]},
  {"i":"RADAR_FORCE_ENABLE","p":["Radar","Control","Force enable the radar"]},
  {"i":"SCREEN_SHAKE","p":["Camera","Shake Screen"]},
  {"i":"TECHTREE_MODIFY_BUILDABILITY_OBJECT","p":["Map","Modify","Adjust the tech tree for a specific object type"]},
  {"i":"WAREHOUSE_SET_VALUE","p":["Unit","Set cash value of Warehouse"]},
  {"i":"SOUND_DISABLE_TYPE","p":["Multimedia","Sound Events","Sound Events -- disable type"]},
  {"i":"SOUND_ENABLE_TYPE","p":["Multimedia","Sound Events","Sound Events -- enable type"]},
  {"i":"SOUND_REMOVE_TYPE","p":["Multimedia","Sound Events","Sound Events -- remove type"]},
  {"i":"SOUND_REMOVE_ALL_DISABLED","p":["Multimedia","Sound Events","Sound Events -- remove all disabled"]},
  {"i":"SOUND_ENABLE_ALL","p":["Multimedia","Sound Events","Sound Events -- enable all"]},
  {"i":"AUDIO_OVERRIDE_VOLUME_TYPE","p":["Multimedia","Sound Events","Sound Events -- override volume -- type"]},
  {"i":"AUDIO_RESTORE_VOLUME_TYPE","p":["Multimedia","Sound Events","Sound Events -- restore volume -- type"]},
  {"i":"AUDIO_RESTORE_VOLUME_ALL_TYPE","p":["Multimedia","Sound Events","Sound Events -- restore volume -- all"]},
  {"i":"NAMED_SET_TOPPLE_DIRECTION","p":["Unit","Set topple direction"]},
  {"i":"UNIT_MOVE_TOWARDS_NEAREST_OBJECT_TYPE","p":["Unit","Move","Move unit towards the nearest object of a specific type"]},
  {"i":"TEAM_MOVE_TOWARDS_NEAREST_OBJECT_TYPE","p":["Team","Move","Move team towards the nearest object of a specific type"]},
  {"i":"SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_ALL","p":["Skirmish","Delay a sequential script until the specified command ability is ready - all"]},
  {"i":"SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_PARTIAL","p":["Skirmish","Delay a sequential script until the specified command ability is ready - partial"]},
  {"i":"TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_OBJECTTYPE","p":["Team","CommandButton","Use command ability -- all -- nearest object type"]},
  {"i":"TEAM_PARTIAL_USE_COMMANDBUTTON","p":["Team","CommandButton","Use command ability -- partial -- self"]},
  {"i":"TEAM_CAPTURE_NEAREST_UNOWNED_FACTION_UNIT","p":["Team","Capture unowned faction unit -- nearest"]},
  {"i":"TEAM_WAIT_FOR_NOT_CONTAINED_ALL","p":["Team","SequentialScript","Delay a sequential script until the team is no longer contained - all"]},
  {"i":"OBJECTLIST_ADDOBJECTTYPE","p":["Scripting","ObjectTypeList","Add Object Type"]},
  {"i":"OBJECTLIST_REMOVEOBJECTTYPE","p":["Scripting","ObjectTypeList","Remove Object Type"]},
  {"i":"MAP_REVEAL_PERMANENTLY_AT_WAYPOINT","p":["Map","Shroud or Reveal","Reveal map at waypoint -- permanently"]},
  {"i":"MAP_UNDO_REVEAL_PERMANENTLY_AT_WAYPOINT","p":["Map","Shroud or Reveal","Reveal map at waypoint -- undo permanently"]},
  {"i":"EVA_SET_ENABLED_DISABLED","p":["Scripting","Enable or Disable EVA"]},
  {"i":"OPTIONS_SET_OCCLUSION_MODE","p":["Scripting","Enable or Disable Occlusion (Drawing Behind Buildings)"]},
  {"i":"OPTIONS_SET_DRAWICON_UI_MODE","p":["Scripting","Enable or Disable Draw-icon UI"]},
  {"i":"OPTIONS_SET_PARTICLE_CAP_MODE","p":["Scripting","Enable or Disable Particle Cap"]},
  {"i":"UNIT_AFFECT_OBJECT_PANEL_FLAGS","p":["Unit","Affect flags set on object panel"]},
  {"i":"TEAM_AFFECT_OBJECT_PANEL_FLAGS","p":["Team","Affect flags set on object panel - all"]},
  {"i":"PLAYER_SELECT_SKILLSET","p":["Player","Set","Set the skillset for a computer player"]},
  {"i":"SCRIPTING_OVERRIDE_HULK_LIFETIME","p":["Scripting","Hulk set override lifetime"]},
  {"i":"NAMED_FACE_NAMED","p":["Unit","Set unit to face another unit"]},
  {"i":"NAMED_FACE_WAYPOINT","p":["Unit","Set unit to face a waypoint"]},
  {"i":"TEAM_FACE_NAMED","p":["Team","Move","Set team to face another unit"]},
  {"i":"TEAM_FACE_WAYPOINT","p":["Team","Move","Set team to face a waypoint"]},
  {"i":"COMMANDBAR_REMOVE_BUTTON_OBJECTTYPE","p":["Scripting","Remove a command button from an object type"]},
  {"i":"COMMANDBAR_ADD_BUTTON_OBJECTTYPE_SLOT","p":["Scripting","Add a command button to an object type"]},
  {"i":"UNIT_SPAWN_NAMED_LOCATION_ORIENTATION","p":["Unit","Spawn","Spawn -- named unit on a team at a position with an orientation"]},
  {"i":"PLAYER_AFFECT_RECEIVING_EXPERIENCE","p":["Player","Experience","Change the modifier to generals experience that a player receives"]},
  {"i":"SOUND_SET_VOLUME","p":["Multimedia","Set the current sound volume"]},
  {"i":"SPEECH_SET_VOLUME","p":["Multimedia","Set the current speech volume"]},
  {"i":"OBJECT_ALLOW_BONUSES","p":["Map","Modify","Adjust Object Bonuses based on difficulty"]},
  {"i":"TEAM_GUARD_IN_TUNNEL_NETWORK","p":["Team","Guard","Set to guard - from inside tunnel network"]},
  {"i":"LOCALDEFEAT","p":["Multiplayer","Announce local defeat"]},
  {"i":"VICTORY","p":["Multiplayer","Announce victory"]},
  {"i":"DEFEAT","p":["Multiplayer","Announce defeat"]},
  {"i":"RESIZE_VIEW_GUARDBAND","p":["Map","Modify","Resize view guardband"]},
  {"i":"DELETE_ALL_UNMANNED","p":["Scripting","Delete all unmanned (sniped) vehicles"]},
  {"i":"CHOOSE_VICTIM_ALWAYS_USES_NORMAL","p":["Map","Modify","Force ChooseVictim to ignore game difficulty and always use Normal setting"]}
];