const SCRIPT_PARAMS={
  "DEBUG_MESSAGE_BOX":{p:["TEXT_STRING"],u:["Show debug string and pause: "]},
  "DEBUG_STRING":{p:["TEXT_STRING"],u:["Show debug string without pausing: "]},
  "DEBUG_CRASH_BOX":{p:["TEXT_STRING"],u:["Display a crash box with the text: "]},
  "SET_FLAG":{p:["FLAG","BOOLEAN"],u:["Set "," to "]},
  "SET_COUNTER":{p:["COUNTER","INT"],u:["Set "," to "]},
  "SET_TREE_SWAY":{p:["ANGLE","ANGLE","ANGLE","INT","REAL"],u:["Set wind direction to ",", amount to sway ",", amount to lean with the wind ",", frames to take to sway once ",", randomness ","(0=lock step, 1=large random variation)."]},
  "SET_INFANTRY_LIGHTING_OVERRIDE":{p:["REAL"],u:["Set lighting percent on infantry to "," (0.0==min, 1.0==normal day, 2.0==max (which is normal night).)"]},
  "RESET_INFANTRY_LIGHTING_OVERRIDE":{p:[],u:["Reset infantry lighting to the normal setting. 1.0 for the two day states, 2.0 for the two night states. (Look in GamesData.ini)"]},
  "QUICKVICTORY":{p:[],u:["End game in victory immediately."]},
  "VICTORY":{p:[],u:["Announce win."]},
  "DEFEAT":{p:[],u:["Announce loss."]},
  "NO_OP":{p:[],u:["Null operation. (Does nothing.)"]},
  "SET_TIMER":{p:["COUNTER","INT"],u:["Set timer "," to expire in "," frames."]},
  "SET_RANDOM_TIMER":{p:["COUNTER","INT","INT"],u:["Set timer "," to expire between "," and "," frames."]},
  "STOP_TIMER":{p:["COUNTER"],u:["Stop timer "]},
  "RESTART_TIMER":{p:["COUNTER"],u:["Restart timer "]},
  "PLAY_SOUND_EFFECT":{p:["SOUND"],u:["Play ","."]},
  "ENABLE_SCRIPT":{p:["SCRIPT"],u:["Enable ","."]},
  "DISABLE_SCRIPT":{p:["SCRIPT"],u:["Disable ","."]},
  "CALL_SUBROUTINE":{p:["SCRIPT_SUBROUTINE"],u:["Run ","."]},
  "PLAY_SOUND_EFFECT_AT":{p:["SOUND","WAYPOINT"],u:["Play "," at ","."]},
  "DAMAGE_MEMBERS_OF_TEAM":{p:["TEAM","REAL"],u:["Damage ",", amount="," (-1==kill)."]},
  "MOVE_TEAM_TO":{p:["TEAM","WAYPOINT"],u:["Move "," to ","."]},
  "TEAM_FOLLOW_WAYPOINTS":{p:["TEAM","WAYPOINT_PATH","BOOLEAN"],u:["Have "," follow "," , as a team is "]},
  "TEAM_FOLLOW_WAYPOINTS_EXACT":{p:["TEAM","WAYPOINT_PATH","BOOLEAN"],u:["Have "," EXACTLY follow "," , as a team is "]},
  "TEAM_WANDER_IN_PLACE":{p:["TEAM"],u:["Have "," wander around its current location."]},
  "TEAM_INCREASE_PRIORITY":{p:["TEAM"],u:["Increase the AI priority for"," by its Success Priority Increase amount."]},
  "TEAM_DECREASE_PRIORITY":{p:["TEAM"],u:["Reduce the AI priority for"," by its Failure Priority Decrease amount."]},
  "TEAM_WANDER":{p:["TEAM","WAYPOINT_PATH"],u:["Have "," wander along "]},
  "TEAM_PANIC":{p:["TEAM","WAYPOINT_PATH"],u:["Have "," move in panic along "]},
  "MOVE_NAMED_UNIT_TO":{p:["UNIT","WAYPOINT"],u:["Move "," to ","."]},
  "TEAM_SET_STATE":{p:["TEAM","TEAM_STATE"],u:["Set "," to ","."]},
  "CREATE_REINFORCEMENT_TEAM":{p:["TEAM","WAYPOINT"],u:["Spawn an instance of "," at ","."]},
  "SKIRMISH_BUILD_BUILDING":{p:["OBJECT_TYPE"],u:["Build a building of type ","."]},
  "AI_PLAYER_BUILD_SUPPLY_CENTER":{p:["SIDE","OBJECT_TYPE","INT"],u:["Have AI "," build a "," near a supply source with at least "," available resources."]},
  "AI_PLAYER_BUILD_TYPE_NEAREST_TEAM":{p:["SIDE","OBJECT_TYPE","TEAM"],u:["Have AI "," build a "," nearest team ","."]},
  "TEAM_GUARD_SUPPLY_CENTER":{p:["TEAM","INT"],u:["Have Team "," guard attacked or closest supply source with at least "," available resources"]},
  "AI_PLAYER_BUILD_UPGRADE":{p:["SIDE","UPGRADE"],u:["Have AI "," build this upgrade: "]},
  "SKIRMISH_FOLLOW_APPROACH_PATH":{p:["TEAM","SKIRMISH_WAYPOINT_PATH","BOOLEAN"],u:["Have "," approach the enemy using path ",", as a team is "]},
  "SKIRMISH_MOVE_TO_APPROACH_PATH":{p:["TEAM","SKIRMISH_WAYPOINT_PATH"],u:["Have "," move to the start of enemy path ","."]},
  "SKIRMISH_BUILD_BASE_DEFENSE_FRONT":{p:[],u:["Build one additional perimeter base defenses, on the front."]},
  "SKIRMISH_BUILD_BASE_DEFENSE_FLANK":{p:[],u:["Build one additional perimeter base defenses, on the flank."]},
  "SKIRMISH_BUILD_STRUCTURE_FRONT":{p:["OBJECT_TYPE"],u:["Build one additional ",", on the front."]},
  "SKIRMISH_BUILD_STRUCTURE_FLANK":{p:["OBJECT_TYPE"],u:["Build one additional ",", on the flank."]},
  "RECRUIT_TEAM":{p:["TEAM","REAL"],u:["Recruit an instance of ",", maximum recruiting distance (feet):","."]},
  "MOVE_CAMERA_TO":{p:["WAYPOINT","REAL","REAL","REAL","REAL"],u:["Move camera to "," in "," seconds, camera shutter "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "ZOOM_CAMERA":{p:["REAL","REAL","REAL","REAL"],u:["Change camera zoom to "," in "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "CAMERA_FADE_ADD":{p:["REAL","REAL","INT","INT","INT"],u:["Fade (0-1) from "," to "," adding toward white. Take "," frames to increase, hold for "," frames, and decrease "," frames."]},
  "CAMERA_FADE_SUBTRACT":{p:["REAL","REAL","INT","INT","INT"],u:["Fade (0-1) from "," to "," subtracting toward black. Take "," frames to increase, hold for "," frames, and decrease "," frames."]},
  "CAMERA_FADE_MULTIPLY":{p:["REAL","REAL","INT","INT","INT"],u:["Fade (1-0) from "," to "," multiplying toward black. Take "," frames to increase, hold for "," frames, and decrease "," frames."]},
  "CAMERA_FADE_SATURATE":{p:["REAL","REAL","INT","INT","INT"],u:["Fade (0.5-1) from "," to "," increasing saturation. Take "," frames to increase, hold for "," frames, and decrease "," frames."]},
  "PITCH_CAMERA":{p:["REAL","REAL","REAL","REAL"],u:["Change camera pitch to "," in "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "CAMERA_FOLLOW_NAMED":{p:["UNIT","BOOLEAN"],u:["Have the camera follow ",".  Snap camera to object is ","."]},
  "CAMERA_STOP_FOLLOW":{p:[],u:["Stop following any units."]},
  "SETUP_CAMERA":{p:["WAYPOINT","REAL","REAL","WAYPOINT"],u:["Position camera at ",", zoom = ","(0.0 to 1.0), pitch = ","(1.0==default), looking towards ","."]},
  "INCREMENT_COUNTER":{p:["INT","COUNTER"],u:["Add "," to counter "]},
  "DECREMENT_COUNTER":{p:["INT","COUNTER"],u:["Subtract "," from counter "]},
  "MOVE_CAMERA_ALONG_WAYPOINT_PATH":{p:["WAYPOINT","REAL","REAL","REAL","REAL"],u:["Move along path starting with "," in "," seconds, camera shutter "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "ROTATE_CAMERA":{p:["REAL","REAL","REAL","REAL"],u:["Rotate "," times, taking "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "RESET_CAMERA":{p:["WAYPOINT","REAL","REAL","REAL"],u:["Reset to ",", taking "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "MOVE_CAMERA_TO_SELECTION":{p:[],u:["End movement at selected unit."]},
  "SET_MILLISECOND_TIMER":{p:["COUNTER","REAL"],u:["Set timer "," to expire in "," seconds."]},
  "SET_RANDOM_MSEC_TIMER":{p:["COUNTER","REAL","REAL"],u:["Set timer "," to expire between "," and "," seconds."]},
  "ADD_TO_MSEC_TIMER":{p:["REAL","COUNTER"],u:["Add "," seconds to timer "," ."]},
  "SUB_FROM_MSEC_TIMER":{p:["REAL","COUNTER"],u:["Subtract "," seconds from timer "," ."]},
  "CAMERA_MOD_FREEZE_TIME":{p:[],u:["Freeze time during the camera movement."]},
  "CAMERA_MOD_FREEZE_ANGLE":{p:[],u:["Freeze camera angle during the camera movement."]},
  "SUSPEND_BACKGROUND_SOUNDS":{p:[],u:["Suspend background sounds."]},
  "RESUME_BACKGROUND_SOUNDS":{p:[],u:["Resume background sounds."]},
  "CAMERA_MOD_SET_FINAL_ZOOM":{p:["REAL","PERCENT","PERCENT"],u:["Adjust zoom to "," (1.0==max height, 0.0==in the ground) "," ease-in "," ease-out."]},
  "CAMERA_MOD_SET_FINAL_PITCH":{p:["REAL","PERCENT","PERCENT"],u:["Adjust pitch to "," (1.0==default, 0.0==toward horizon, >1 = toward ground) "," ease-in "," ease-out."]},
  "SET_VISUAL_SPEED_MULTIPLIER":{p:["INT"],u:["Make visual time "," time normal (1=normal, 2 = twice as fast, ...)."]},
  "CAMERA_MOD_SET_FINAL_SPEED_MULTIPLIER":{p:["INT"],u:["Adjust game time to"," times normal (1=normal, 2 = twice as fast, ...)."]},
  "CAMERA_MOD_SET_ROLLING_AVERAGE":{p:["INT"],u:["Average position and angle changes over"," frames. (1=no smoothing, 5 = very smooth)"]},
  "CAMERA_MOD_FINAL_LOOK_TOWARD":{p:["WAYPOINT"],u:["Look toward"," at the end of the camera movement."]},
  "CAMERA_MOD_LOOK_TOWARD":{p:["WAYPOINT"],u:["Look toward"," during the camera movement."]},
  "CREATE_OBJECT":{p:["OBJECT_TYPE","TEAM","COORD3D","ANGLE"],u:["Spawn object "," in "," at position (","), rotated "," ."]},
  "TEAM_ATTACK_TEAM":{p:["TEAM","TEAM"],u:[" "," begin attack on "]},
  "NAMED_ATTACK_NAMED":{p:["UNIT","UNIT"],u:[" "," begin attack on "]},
  "CREATE_NAMED_ON_TEAM_AT_WAYPOINT":{p:["UNIT","OBJECT_TYPE","TEAM","WAYPOINT"],u:["Spawn "," of type "," on "," at waypoint "]},
  "CREATE_UNNAMED_ON_TEAM_AT_WAYPOINT":{p:["OBJECT_TYPE","TEAM","WAYPOINT"],u:["Spawn unit of type "," on "," at waypoint "]},
  "NAMED_APPLY_ATTACK_PRIORITY_SET":{p:["UNIT","ATTACK_PRIORITY_SET"],u:["Have "," use ","."]},
  "TEAM_APPLY_ATTACK_PRIORITY_SET":{p:["TEAM","ATTACK_PRIORITY_SET"],u:["Have "," use ","."]},
  "SET_ATTACK_PRIORITY_THING":{p:["ATTACK_PRIORITY_SET","OBJECT_TYPE","INT"],u:["For "," set the priority of object type "," to "]},
  "SET_ATTACK_PRIORITY_KIND_OF":{p:["ATTACK_PRIORITY_SET","KIND_OF_PARAM","INT"],u:["For "," set the priority of object type "," to "]},
  "SET_DEFAULT_ATTACK_PRIORITY":{p:["ATTACK_PRIORITY_SET","INT"],u:["For "," set the default priority to "]},
  "PLAYER_ADD_SKILLPOINTS":{p:["SIDE","INT"],u:[" "," is given "," Skill Points."]},
  "PLAYER_ADD_RANKLEVEL":{p:["SIDE","INT"],u:[" "," is given "," Rank Levels."]},
  "PLAYER_SET_RANKLEVEL":{p:["SIDE","INT"],u:[" "," is given a Rank Level of ","."]},
  "PLAYER_SET_RANKLEVELLIMIT":{p:["INT"],u:["The current map is given a Rank Level Limit of ","."]},
  "PLAYER_GRANT_SCIENCE":{p:["SIDE","SCIENCE"],u:[" "," is granted ","."]},
  "PLAYER_PURCHASE_SCIENCE":{p:["SIDE","SCIENCE"],u:[" "," attempts to purchase Science ","."]},
  "PLAYER_SCIENCE_AVAILABILITY":{p:["SIDE","SCIENCE","SCIENCE_AVAILABILITY"],u:[" "," set "," availability to ","."]},
  "SET_BASE_CONSTRUCTION_SPEED":{p:["SIDE","INT"],u:[" "," will delay "," seconds between building teams."]},
  "NAMED_SET_ATTITUDE":{p:["UNIT","AI_MOOD"],u:[" "," changes his attitude to "]},
  "TEAM_SET_ATTITUDE":{p:["TEAM","AI_MOOD"],u:[" "," change their attitude to "]},
  "NAMED_SET_REPULSOR":{p:["UNIT","BOOLEAN"],u:[" "," REPULSOR flag is "]},
  "TEAM_SET_REPULSOR":{p:["TEAM","BOOLEAN"],u:[" "," REPULSOR flag is "]},
  "NAMED_ATTACK_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," attacks anything in "]},
  "NAMED_ATTACK_TEAM":{p:["UNIT","TEAM"],u:[" "," attacks "]},
  "TEAM_ATTACK_AREA":{p:["TEAM","TRIGGER_AREA"],u:[" "," attack anything in "]},
  "TEAM_ATTACK_NAMED":{p:["TEAM","UNIT"],u:[" "," attacks "]},
  "TEAM_LOAD_TRANSPORTS":{p:["TEAM"],u:[" "," load into transports."]},
  "NAMED_ENTER_NAMED":{p:["UNIT","UNIT"],u:[" "," loads into "]},
  "TEAM_ENTER_NAMED":{p:["TEAM","UNIT"],u:[" "," attempt to load into "]},
  "NAMED_EXIT_ALL":{p:["UNIT"],u:[" "," unloads."]},
  "TEAM_EXIT_ALL":{p:["TEAM"],u:[" "," unload."]},
  "NAMED_FOLLOW_WAYPOINTS":{p:["UNIT","WAYPOINT_PATH"],u:[" "," follows waypoints, beginning at "]},
  "NAMED_FOLLOW_WAYPOINTS_EXACT":{p:["UNIT","WAYPOINT_PATH"],u:[" "," EXACTLY follows waypoints, beginning at "]},
  "NAMED_GUARD":{p:["UNIT"],u:[" "," begins guarding."]},
  "TEAM_GUARD":{p:["TEAM"],u:[" "," begins guarding."]},
  "TEAM_GUARD_POSITION":{p:["TEAM","WAYPOINT"],u:[" "," begins guarding at "]},
  "TEAM_GUARD_OBJECT":{p:["TEAM","UNIT"],u:[" "," begins guarding "]},
  "TEAM_GUARD_AREA":{p:["TEAM","TRIGGER_AREA"],u:[" "," begins guarding "]},
  "NAMED_HUNT":{p:["UNIT"],u:[" "," begins hunting."]},
  "TEAM_HUNT_WITH_COMMAND_BUTTON":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," begins hunting using ","."]},
  "TEAM_HUNT":{p:["TEAM"],u:[" "," begins hunting."]},
  "PLAYER_HUNT":{p:["SIDE"],u:[" "," begins hunting."]},
  "PLAYER_SELL_EVERYTHING":{p:["SIDE"],u:[" "," sells everything."]},
  "PLAYER_DISABLE_BASE_CONSTRUCTION":{p:["SIDE"],u:[" "," is unable to build buildings."]},
  "PLAYER_DISABLE_FACTORIES":{p:["SIDE","OBJECT_TYPE"],u:[" "," is unable to build from "]},
  "PLAYER_DISABLE_UNIT_CONSTRUCTION":{p:["SIDE"],u:[" "," is unable to build units."]},
  "PLAYER_ENABLE_BASE_CONSTRUCTION":{p:["SIDE"],u:[" "," is able to build buildings."]},
  "PLAYER_ENABLE_FACTORIES":{p:["SIDE","OBJECT_TYPE"],u:[" "," is able to build from "]},
  "PLAYER_ENABLE_UNIT_CONSTRUCTION":{p:["SIDE"],u:[" "," is able to build units."]},
  "CAMERA_MOVE_HOME":{p:[],u:["The camera moves to the home base."]},
  "OVERSIZE_TERRAIN":{p:["INT"],u:["Oversize the terrain "," tiles on each side [0 = reset to normal]."]},
  "BUILD_TEAM":{p:["TEAM"],u:["Start building team "]},
  "NAMED_DAMAGE":{p:["UNIT","INT"],u:[" "," takes "," points of damage."]},
  "NAMED_DELETE":{p:["UNIT"],u:[" "," is removed from the world."]},
  "TEAM_DELETE":{p:["TEAM"],u:[" "," is removed from the world."]},
  "TEAM_DELETE_LIVING":{p:["TEAM"],u:["Each living member of team "," is removed from the world."]},
  "NAMED_KILL":{p:["UNIT"],u:[" ","is dealt a lethal amount of damage."]},
  "TEAM_KILL":{p:["TEAM"],u:[" "," is dealt a lethal amount of damage."]},
  "PLAYER_KILL":{p:["SIDE"],u:["All of ","'s buildings and units are dealt a lethal amount of damage."]},
  "DISPLAY_TEXT":{p:["LOCALIZED_TEXT"],u:["Displays "," in the text log and message area."]},
  "DISPLAY_CINEMATIC_TEXT":{p:["LOCALIZED_TEXT","FONT_NAME","INT"],u:["Displays "," with font type "," in the bottom letterbox for "," seconds."]},
  "CAMEO_FLASH":{p:["COMMAND_BUTTON","INT"],u:[" "," flashes for "," seconds."]},
  "NAMED_FLASH":{p:["UNIT","INT"],u:[" "," flashes for "," seconds."]},
  "TEAM_FLASH":{p:["TEAM","INT"],u:[" "," flashes for "," seconds."]},
  "NAMED_CUSTOM_COLOR":{p:["UNIT","COLOR"],u:[" "," uses the color "," ."]},
  "NAMED_FLASH_WHITE":{p:["UNIT","INT"],u:[" "," flashes white for "," seconds."]},
  "TEAM_FLASH_WHITE":{p:["TEAM","INT"],u:[" "," flashes white for "," seconds."]},
  "INGAME_POPUP_MESSAGE":{p:["LOCALIZED_TEXT","INT","INT","INT","BOOLEAN"],u:["Displays "," at "," percent of the screen Width "," percent of the screen Height and a width of "," pixels and pauses the game ("," )"]},
  "MOVIE_PLAY_FULLSCREEN":{p:["MOVIE"],u:[" "," plays fullscreen."]},
  "MOVIE_PLAY_RADAR":{p:["MOVIE"],u:[" "," plays in the radar window."]},
  "SOUND_PLAY_NAMED":{p:["TEXT_STRING","UNIT"],u:[" "," plays as though coming from "]},
  "SPEECH_PLAY":{p:["DIALOG","BOOLEAN"],u:[" "," plays, allowing overlap "," (true to allow, false to disallow)."]},
  "PLAYER_TRANSFER_OWNERSHIP_PLAYER":{p:["SIDE","SIDE"],u:["All assets of "," are transferred to "]},
  "NAMED_TRANSFER_OWNERSHIP_PLAYER":{p:["UNIT","SIDE"],u:[" "," is transferred to the command of "]},
  "PLAYER_EXCLUDE_FROM_SCORE_SCREEN":{p:["SIDE"],u:["Exclude "," from the score screen."]},
  "ENABLE_SCORING":{p:[],u:["Turn on scoring."]},
  "DISABLE_SCORING":{p:[],u:["Turn off scoring."]},
  "PLAYER_RELATES_PLAYER":{p:["SIDE","SIDE","RELATION"],u:[" "," considers "," to be "]},
  "RADAR_CREATE_EVENT":{p:["COORD3D","RADAR_EVENT_TYPE"],u:["A radar event occurs at "," of type "]},
  "OBJECT_CREATE_RADAR_EVENT":{p:["UNIT","RADAR_EVENT_TYPE"],u:["A radar event occurs at "," of type "]},
  "TEAM_CREATE_RADAR_EVENT":{p:["TEAM","RADAR_EVENT_TYPE"],u:["A radar event occurs at "," of type "]},
  "RADAR_DISABLE":{p:[],u:["The radar is disabled."]},
  "RADAR_ENABLE":{p:[],u:["The radar is enabled."]},
  "NAMED_SET_STEALTH_ENABLED":{p:["UNIT","BOOLEAN"],u:["Set "," stealth ability to ","."]},
  "TEAM_SET_STEALTH_ENABLED":{p:["TEAM","BOOLEAN"],u:["Set "," stealth ability to ","."]},
  "NAMED_SET_UNMANNED_STATUS":{p:["UNIT"],u:["Make "," unmanned."]},
  "TEAM_SET_UNMANNED_STATUS":{p:["TEAM"],u:["Make "," unmanned."]},
  "NAMED_SET_BOOBYTRAPPED":{p:["OBJECT_TYPE","UNIT"],u:["Add boobytrap of type "," to ","."]},
  "TEAM_SET_BOOBYTRAPPED":{p:["OBJECT_TYPE","TEAM"],u:["Add boobytrap of type "," to team ","."]},
  "MAP_REVEAL_AT_WAYPOINT":{p:["WAYPOINT","REAL","SIDE"],u:["The map is revealed at "," with a radius of "," feet for ","."]},
  "MAP_SHROUD_AT_WAYPOINT":{p:["WAYPOINT","REAL","SIDE"],u:["The map is shrouded at "," with a radius of "," feet for ","."]},
  "MAP_REVEAL_ALL":{p:["SIDE"],u:["The world is revealed for ","."]},
  "MAP_REVEAL_ALL_PERM":{p:["SIDE"],u:["The world is revealed permanently for ","."]},
  "MAP_REVEAL_ALL_UNDO_PERM":{p:["SIDE"],u:["Undo the permanent reveal for ",".  This will mess things up badly if called when there has been no permanent reveal."]},
  "MAP_SHROUD_ALL":{p:["SIDE"],u:["The world is shrouded for ","."]},
  "DISABLE_BORDER_SHROUD":{p:[],u:["Shroud off the map edges is turned off."]},
  "ENABLE_BORDER_SHROUD":{p:[],u:["Shroud off the map edges is turned on."]},
  "TEAM_GARRISON_SPECIFIC_BUILDING":{p:["TEAM","UNIT"],u:[" "," enters into building named "]},
  "EXIT_SPECIFIC_BUILDING":{p:["UNIT"],u:[" "," empties."]},
  "TEAM_GARRISON_NEAREST_BUILDING":{p:["TEAM"],u:[" "," garrison a nearby building."]},
  "TEAM_EXIT_ALL_BUILDINGS":{p:["TEAM"],u:[" "," exits all buildings."]},
  "NAMED_GARRISON_SPECIFIC_BUILDING":{p:["UNIT","UNIT"],u:[" "," garrison building "]},
  "NAMED_GARRISON_NEAREST_BUILDING":{p:["UNIT"],u:[" "," garrison a nearby building."]},
  "NAMED_EXIT_BUILDING":{p:["UNIT"],u:[" "," leaves the building."]},
  "PLAYER_GARRISON_ALL_BUILDINGS":{p:["SIDE"],u:[" "," garrison buildings."]},
  "PLAYER_EXIT_ALL_BUILDINGS":{p:["SIDE"],u:[" "," evacuate."]},
  "TEAM_AVAILABLE_FOR_RECRUITMENT":{p:["TEAM","BOOLEAN"],u:[" "," sets their willingness to join teams to "]},
  "TEAM_COLLECT_NEARBY_FOR_TEAM":{p:["TEAM"],u:[" "," attempts to collect nearby units for a team."]},
  "TEAM_MERGE_INTO_TEAM":{p:["TEAM","TEAM"],u:[" "," merges onto "]},
  "IDLE_ALL_UNITS":{p:[],u:["Idle all units for all players."]},
  "RESUME_SUPPLY_TRUCKING":{p:[],u:["All idle Supply Trucks attempt to resume supply routes."]},
  "DISABLE_INPUT":{p:[],u:["Disable mouse and keyboard input."]},
  "ENABLE_INPUT":{p:[],u:["Enable mouse and keyboard input."]},
  "SOUND_AMBIENT_PAUSE":{p:[],u:["Pause the ambient sounds."]},
  "SOUND_AMBIENT_RESUME":{p:[],u:["Resume the ambient sounds."]},
  "MUSIC_SET_TRACK":{p:["MUSIC","BOOLEAN","BOOLEAN"],u:["Play "," using fadeout (",") and fadein (",")."]},
  "CAMERA_LETTERBOX_BEGIN":{p:[],u:["Start letterbox mode (hide UI, add border)."]},
  "CAMERA_LETTERBOX_END":{p:[],u:["End letterbox mode (show UI, remove border)."]},
  "CAMERA_BW_MODE_BEGIN":{p:["INT"],u:["Frames to fade into black & white mode = "]},
  "CAMERA_BW_MODE_END":{p:[],u:["Frames to fade into color mode = "]},
  "CAMERA_MOTION_BLUR":{p:["BOOLEAN","BOOLEAN"],u:["Blur zoom, zoom in = "," (true=zoom in, false = zoom out), saturate colors = "]},
  "CAMERA_MOTION_BLUR_JUMP":{p:["WAYPOINT","BOOLEAN"],u:["Blur zoom, zoom in at current location, zoom out at ",", saturate colors = "]},
  "CAMERA_MOTION_BLUR_FOLLOW":{p:["INT"],u:["Start motion blur as the camera moves, amount= "," (start with 30 and adjust up or down). "]},
  "CAMERA_MOTION_BLUR_END_FOLLOW":{p:[],u:["End motion blur as the camera moves."]},
  "DRAW_SKYBOX_BEGIN":{p:[],u:["Start skybox mode (draw sky background)."]},
  "DRAW_SKYBOX_END":{p:[],u:["End skybox mode (draw black background)."]},
  "FREEZE_TIME":{p:[],u:["Freeze time."]},
  "UNFREEZE_TIME":{p:[],u:["Unfreeze time."]},
  "SHOW_MILITARY_CAPTION":{p:["TEXT_STRING","INT"],u:["Show military briefing "," for "," milliseconds."]},
  "CAMERA_SET_AUDIBLE_DISTANCE":{p:["REAL"],u:["Set the audible range during camera-up shots to "]},
  "NAMED_SET_HELD":{p:["UNIT","BOOLEAN"],u:["Set Held status for "," to ","."]},
  "NAMED_SET_STOPPING_DISTANCE":{p:["UNIT","REAL"],u:["Set stopping distance for "," to ","."]},
  "SET_STOPPING_DISTANCE":{p:["TEAM","REAL"],u:["Set stopping distances for "," to ","."]},
  "SET_FPS_LIMIT":{p:["INT"],u:["Set max FPS to ",".  (0 sets to default.)"]},
  "DISABLE_SPECIAL_POWER_DISPLAY":{p:[],u:["Disables special power countdown display."]},
  "ENABLE_SPECIAL_POWER_DISPLAY":{p:[],u:["Enables special power countdown display."]},
  "NAMED_HIDE_SPECIAL_POWER_DISPLAY":{p:["UNIT"],u:["Hides special power countdowns for ","."]},
  "NAMED_SHOW_SPECIAL_POWER_DISPLAY":{p:["UNIT"],u:["Shows special power countdowns for ","."]},
  "MUSIC_SET_VOLUME":{p:["REAL"],u:["Set the desired music volume to ","%. (0-100)"]},
  "TEAM_TRANSFER_TO_PLAYER":{p:["TEAM","SIDE"],u:["Control of "," transfers to "]},
  "PLAYER_SET_MONEY":{p:["SIDE","INT"],u:["Set ","'s money to $"]},
  "PLAYER_GIVE_MONEY":{p:["SIDE","INT"],u:[" "," gets $"]},
  "DISPLAY_COUNTER":{p:["COUNTER","LOCALIZED_TEXT"],u:["Show "," with text "]},
  "HIDE_COUNTER":{p:["COUNTER"],u:["Hide "]},
  "DISPLAY_COUNTDOWN_TIMER":{p:["COUNTER","LOCALIZED_TEXT"],u:["Show "," with text "]},
  "HIDE_COUNTDOWN_TIMER":{p:["COUNTER"],u:["Hide "]},
  "DISABLE_COUNTDOWN_TIMER_DISPLAY":{p:[],u:["Disables timer display."]},
  "ENABLE_COUNTDOWN_TIMER_DISPLAY":{p:[],u:["Enables timer display."]},
  "NAMED_STOP_SPECIAL_POWER_COUNTDOWN":{p:["UNIT","SPECIAL_POWER"],u:["Pause ","'s "," countdown."]},
  "NAMED_START_SPECIAL_POWER_COUNTDOWN":{p:["UNIT","SPECIAL_POWER"],u:["Resume ","'s "," countdown."]},
  "NAMED_SET_SPECIAL_POWER_COUNTDOWN":{p:["UNIT","SPECIAL_POWER","INT"],u:["Set ","'s "," to "," seconds."]},
  "NAMED_ADD_SPECIAL_POWER_COUNTDOWN":{p:["UNIT","SPECIAL_POWER","INT"],u:[" ","'s "," has "," seconds added to it."]},
  "SKIRMISH_FIRE_SPECIAL_POWER_AT_MOST_COST":{p:["SIDE","SPECIAL_POWER"],u:[" "," fire "," at enemy's most costly area."]},
  "PLAYER_REPAIR_NAMED_STRUCTURE":{p:["SIDE","UNIT"],u:["Have "," repair ","."]},
  "NAMED_FIRE_SPECIAL_POWER_AT_WAYPOINT":{p:["UNIT","SPECIAL_POWER","WAYPOINT"],u:[" "," fires "," at ","."]},
  "NAMED_FIRE_SPECIAL_POWER_AT_NAMED":{p:["UNIT","SPECIAL_POWER","UNIT"],u:[" "," fires "," at ","."]},
  "REFRESH_RADAR":{p:[],u:["Refresh radar terrain."]},
  "NAMED_STOP":{p:["UNIT"],u:[" "," stops."]},
  "TEAM_STOP":{p:["TEAM"],u:[" "," stops."]},
  "TEAM_STOP_AND_DISBAND":{p:["TEAM"],u:[" "," stops, then disbands."]},
  "TEAM_SET_OVERRIDE_RELATION_TO_TEAM":{p:["TEAM","TEAM","RELATION"],u:[" "," considers "," to be "," (rather than using the player relationship)."]},
  "TEAM_REMOVE_OVERRIDE_RELATION_TO_TEAM":{p:["TEAM","TEAM"],u:[" "," uses the player relationship to "]},
  "TEAM_REMOVE_ALL_OVERRIDE_RELATIONS":{p:["TEAM"],u:[" "," uses the player relationship to all other teams and players."]},
  "CAMERA_TETHER_NAMED":{p:["UNIT","BOOLEAN","REAL"],u:["Have the camera tethered to ",".  Snap camera to object is ",".  Amount of play is ","."]},
  "CAMERA_STOP_TETHER_NAMED":{p:[],u:["Stop tether to any units."]},
  "CAMERA_SET_DEFAULT":{p:["REAL","REAL","REAL"],u:["Camera Pitch = ","(0.0==default), angle = ","(0.0 is N, 90.0 is W, etc), height = ","(1.0==default)."]},
  "CAMERA_LOOK_TOWARD_OBJECT":{p:["UNIT","REAL","REAL","REAL","REAL"],u:["Rotate toward ",", taking "," seconds and holding "," seconds, ease-in "," seconds, ease-out "," seconds."]},
  "CAMERA_LOOK_TOWARD_WAYPOINT":{p:["WAYPOINT","REAL","REAL","REAL","BOOLEAN"],u:["Rotate to look at ",", taking "," seconds, ease-in "," seconds, ease-out "," seconds, reverse rotation ","."]},
  "UNIT_DESTROY_ALL_CONTAINED":{p:["UNIT","INT"],u:["All units inside "," are killed."]},
  "NAMED_FIRE_WEAPON_FOLLOWING_WAYPOINT_PATH":{p:["UNIT","WAYPOINT_PATH"],u:[" "," fire waypoint-weapon following waypoints starting at ","."]},
  "TEAM_SET_OVERRIDE_RELATION_TO_PLAYER":{p:["TEAM","SIDE","RELATION"],u:[" "," considers "," to be "," (rather than using the player relationship)."]},
  "TEAM_REMOVE_OVERRIDE_RELATION_TO_PLAYER":{p:["TEAM","SIDE"],u:[" "," uses the player relationship to "]},
  "PLAYER_SET_OVERRIDE_RELATION_TO_TEAM":{p:["SIDE","TEAM","RELATION"],u:[" "," considers "," to be "," (rather than using the player relationship)."]},
  "PLAYER_REMOVE_OVERRIDE_RELATION_TO_TEAM":{p:["SIDE","TEAM"],u:[" "," uses the player relationship to "]},
  "UNIT_EXECUTE_SEQUENTIAL_SCRIPT":{p:["UNIT","SCRIPT"],u:[" "," executes "," sequentially."]},
  "UNIT_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING":{p:["UNIT","SCRIPT","INT"],u:[" "," executes "," sequentially, "," times. (0=forever)"]},
  "TEAM_EXECUTE_SEQUENTIAL_SCRIPT":{p:["TEAM","SCRIPT"],u:[" "," executes "," sequentially."]},
  "TEAM_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING":{p:["TEAM","SCRIPT","INT"],u:[" "," executes "," sequentially, "," times. (0=forever)"]},
  "UNIT_STOP_SEQUENTIAL_SCRIPT":{p:["UNIT"],u:[" "," stops executing."]},
  "TEAM_STOP_SEQUENTIAL_SCRIPT":{p:["TEAM"],u:[" "," stops executing."]},
  "UNIT_GUARD_FOR_FRAMECOUNT":{p:["UNIT","INT"],u:[" "," guards for "," frames."]},
  "UNIT_IDLE_FOR_FRAMECOUNT":{p:["UNIT","INT"],u:[" "," idles for "," frames."]},
  "TEAM_GUARD_FOR_FRAMECOUNT":{p:["TEAM","INT"],u:[" "," guards for "," frames."]},
  "TEAM_IDLE_FOR_FRAMECOUNT":{p:["TEAM","INT"],u:[" "," idles for "," frames."]},
  "WATER_CHANGE_HEIGHT":{p:["TRIGGER_AREA","REAL"],u:[" "," changes altitude to "]},
  "WATER_CHANGE_HEIGHT_OVER_TIME":{p:["TRIGGER_AREA","REAL","REAL","REAL"],u:[" "," changes altitude to "," in "," seconds doing "," dam_/sec."]},
  "NAMED_USE_COMMANDBUTTON_ABILITY":{p:["UNIT","COMMANDBUTTON_ABILITY"],u:[" "," use ","."]},
  "NAMED_USE_COMMANDBUTTON_ABILITY_ON_NAMED":{p:["UNIT","COMMANDBUTTON_ABILITY","UNIT"],u:[" "," use "," on ","."]},
  "NAMED_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT":{p:["UNIT","COMMANDBUTTON_ABILITY","WAYPOINT"],u:[" "," use "," at ","."]},
  "NAMED_USE_COMMANDBUTTON_ABILITY_USING_WAYPOINT_PATH":{p:["UNIT","COMMANDBUTTON_ABILITY","WAYPOINT_PATH"],u:[" "," use "," to follow "," path."]},
  "TEAM_USE_COMMANDBUTTON_ABILITY":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," use ","."]},
  "TEAM_USE_COMMANDBUTTON_ABILITY_ON_NAMED":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","UNIT"],u:[" "," use "," on ","."]},
  "TEAM_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","WAYPOINT"],u:[" "," use "," at ","."]},
  "MAP_SWITCH_BORDER":{p:["BOUNDARY"],u:[" "," becomes the active border."]},
  "OBJECT_FORCE_SELECT":{p:["TEAM","OBJECT_TYPE","BOOLEAN","DIALOG"],u:[" "," 's first ",", centers in view (",") while playing "]},
  "RADAR_FORCE_ENABLE":{p:[],u:["The radar is now forced to be enabled."]},
  "RADAR_REVERT_TO_NORMAL":{p:[],u:["The radar is now reverting to its normal behavior."]},
  "SCREEN_SHAKE":{p:["SHAKE_INTENSITY"],u:["The screen will shake with "]},
  "TECHTREE_MODIFY_BUILDABILITY_OBJECT":{p:["OBJECT_TYPE","BUILDABLE"],u:[" "," becomes "]},
  "SET_CAVE_INDEX":{p:["UNIT","INT"],u:["Cave named "," is set to being connected to all caves of index ",", but only if both Cave listings have no occupants. "]},
  "WAREHOUSE_SET_VALUE":{p:["UNIT","INT"],u:["Warehouse named "," is set to having "," dollars worth of boxes. "]},
  "SOUND_DISABLE_TYPE":{p:["SOUND"],u:[" "," is disabled."]},
  "SOUND_ENABLE_TYPE":{p:["SOUND"],u:[" "," is enabled."]},
  "SOUND_REMOVE_TYPE":{p:["SOUND"],u:[" "," is removed."]},
  "SOUND_REMOVE_ALL_DISABLED":{p:[],u:["Remove all disabled sound events."]},
  "SOUND_ENABLE_ALL":{p:[],u:["Enable all sound events."]},
  "AUDIO_OVERRIDE_VOLUME_TYPE":{p:["SOUND","REAL"],u:[" "," play at ","% of full volume."]},
  "AUDIO_RESTORE_VOLUME_TYPE":{p:["SOUND"],u:[" "," play at normal volume."]},
  "AUDIO_RESTORE_VOLUME_ALL_TYPE":{p:[],u:["All sound events play at normal volume."]},
  "NAMED_SET_TOPPLE_DIRECTION":{p:["UNIT","COORD3D"],u:[" "," will topple towards "," if destroyed."]},
  "UNIT_MOVE_TOWARDS_NEAREST_OBJECT_TYPE":{p:["UNIT","OBJECT_TYPE","TRIGGER_AREA"],u:[" "," will move towards the nearest "," within "]},
  "TEAM_MOVE_TOWARDS_NEAREST_OBJECT_TYPE":{p:["TEAM","OBJECT_TYPE","TRIGGER_AREA"],u:[" "," will move towards the nearest "," within "]},
  "SKIRMISH_ATTACK_NEAREST_GROUP_WITH_VALUE":{p:["TEAM","COMPARISON","INT"],u:[" "," attacks nearest group worth "," "]},
  "SKIRMISH_PERFORM_COMMANDBUTTON_ON_MOST_VALUABLE_OBJECT":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","REAL","BOOLEAN"],u:[" "," performs "," on most expensive object within "," "," (true = all valid sources, false = first valid source)."]},
  "SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_ALL":{p:["SIDE","TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," 's "," all wait until "," is ready."]},
  "SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_PARTIAL":{p:["SIDE","TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," 's "," wait until at least one member is "," ready."]},
  "TEAM_SPIN_FOR_FRAMECOUNT":{p:["TEAM","INT"],u:[" "," continue their current action for at least "," frames."]},
  "CAMERA_FADE_MULTIPLY":{p:[],u:[]},
  "CAMERA_ENABLE_SLAVE_MODE":{p:["TEXT_STRING","TEXT_STRING"],u:["Enable 3DSMax Camera playback of animation with thing name "," containing bone name "]},
  "CAMERA_DISABLE_SLAVE_MODE":{p:[],u:["Disable camera playback mode."]},
  "CAMERA_ADD_SHAKER_AT":{p:["WAYPOINT","REAL","REAL","REAL"],u:["Add Camera Shaker Effect at waypoint "," with Amplitude "," Duration (seconds) "," Radius."]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NAMED":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","UNIT"],u:[" "," use "," on "]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_UNIT":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," use "," on nearest enemy unit."]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_GARRISONED_BUILDING":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," use "," on nearest enemy garrisoned building."]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_KINDOF":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","KIND_OF_PARAM"],u:[" "," use "," on nearest enemy with ","."]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_BUILDING":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" "," use "," on nearest enemy building."]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_ENEMY_BUILDING_CLASS":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","KIND_OF_PARAM"],u:[" "," use "," on nearest enemy building with "]},
  "TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_OBJECTTYPE":{p:["TEAM","COMMANDBUTTON_ALL_ABILITIES","OBJECT_TYPE"],u:[" "," use "," on nearest object of type ","."]},
  "TEAM_PARTIAL_USE_COMMANDBUTTON":{p:["REAL","TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" ","% of "," perform ","."]},
  "TEAM_CAPTURE_NEAREST_UNOWNED_FACTION_UNIT":{p:["TEAM"],u:[" "," capture the nearest unowned faction unit."]},
  "PLAYER_CREATE_TEAM_FROM_CAPTURED_UNITS":{p:["SIDE","TEAM"],u:[" "," creates a new "," from units it has captured. (There's nothing quite like being assaulted by your own captured units!)"]},
  "TEAM_WAIT_FOR_NOT_CONTAINED_ALL":{p:["TEAM"],u:[" "," all delay until they are no longer contained."]},
  "TEAM_WAIT_FOR_NOT_CONTAINED_PARTIAL":{p:["TEAM"],u:[" "," delay until at least one of them is no longer contained."]},
  "TEAM_SET_EMOTICON":{p:["TEAM","EMOTICON","REAL"],u:[" "," use "," emoticon for "," seconds."]},
  "NAMED_SET_EMOTICON":{p:["UNIT","EMOTICON","REAL"],u:[" "," use "," emoticon for "," seconds."]},
  "OBJECTLIST_ADDOBJECTTYPE":{p:["OBJECT_TYPE_LIST","OBJECT_TYPE"],u:[" "," : add "]},
  "OBJECTLIST_REMOVEOBJECTTYPE":{p:["OBJECT_TYPE_LIST","OBJECT_TYPE"],u:[" "," : remove "]},
  "MAP_REVEAL_PERMANENTLY_AT_WAYPOINT":{p:["WAYPOINT","REAL","SIDE","REVEALNAME"],u:["The map is permanently revealed at "," with a radius of "," for ",". (Afterwards referred to as ",")."]},
  "MAP_UNDO_REVEAL_PERMANENTLY_AT_WAYPOINT":{p:["REVEALNAME"],u:[" "," is undone."]},
  "EVA_SET_ENABLED_DISABLED":{p:["BOOLEAN"],u:["Set EVA to be enabled "," (False to disable.)"]},
  "OPTIONS_SET_OCCLUSION_MODE":{p:["BOOLEAN"],u:["Set Occlusion to be enabled "," (False to disable.)"]},
  "OPTIONS_SET_DRAWICON_UI_MODE":{p:["BOOLEAN"],u:["Set Draw-icon UI to be enabled "," (False to disable.)"]},
  "OPTIONS_SET_PARTICLE_CAP_MODE":{p:["BOOLEAN"],u:["Set Particle Cap to be enabled "," (False to disable.)"]},
  "UNIT_AFFECT_OBJECT_PANEL_FLAGS":{p:["UNIT","OBJECT_PANEL_FLAG","BOOLEAN"],u:[" "," changes the value of flag "," to ","."]},
  "TEAM_AFFECT_OBJECT_PANEL_FLAGS":{p:["TEAM","OBJECT_PANEL_FLAG","BOOLEAN"],u:[" "," change the value of flag "," to ","."]},
  "PLAYER_SELECT_SKILLSET":{p:["SIDE","INT"],u:[" "," uses skillset number "," (1-5)."]},
  "SCRIPTING_OVERRIDE_HULK_LIFETIME":{p:["REAL"],u:["Override hulk lifetime to "," seconds. Negative value reverts to normal behavior."]},
  "NAMED_FACE_NAMED":{p:["UNIT","UNIT"],u:[" "," begin facing "]},
  "NAMED_FACE_WAYPOINT":{p:["UNIT","WAYPOINT"],u:[" "," begin facing "]},
  "TEAM_FACE_NAMED":{p:["TEAM","UNIT"],u:[" "," begin facing "]},
  "TEAM_FACE_WAYPOINT":{p:["TEAM","WAYPOINT"],u:[" "," begin facing "]},
  "COMMANDBAR_REMOVE_BUTTON_OBJECTTYPE":{p:["COMMAND_BUTTON","OBJECT_TYPE"],u:[" "," is removed from all objects of type ","."]},
  "COMMANDBAR_ADD_BUTTON_OBJECTTYPE_SLOT":{p:["COMMAND_BUTTON","OBJECT_TYPE","INT"],u:[" "," is added to all objects of type "," in slot number "," (1-12)."]},
  "UNIT_SPAWN_NAMED_LOCATION_ORIENTATION":{p:["UNIT","OBJECT_TYPE","TEAM","COORD3D","ANGLE"],u:["Spawn "," of type "," on team "," at position (","), rotated "," ."]},
  "PLAYER_AFFECT_RECEIVING_EXPERIENCE":{p:["SIDE","REAL"],u:[" "," gains experience at "," times the usual rate (0.0 for no gain, 1.0 for normal rate)"]},
  "SOUND_SET_VOLUME":{p:["REAL"],u:["Set the desired sound volume to ","%. (0-100)"]},
  "SPEECH_SET_VOLUME":{p:["REAL"],u:["Set the desired speech volume to ","%. (0-100)"]},
  "OBJECT_ALLOW_BONUSES":{p:["BOOLEAN"],u:["Enable Object Bonuses based on difficulty "," (true to enable, false to disable)."]},
  "TEAM_GUARD_IN_TUNNEL_NETWORK":{p:["TEAM"],u:[" "," Enter and guard from tunnel network."]},
  "LOCALDEFEAT":{p:[],u:["Show 'Game Over' window"]},
  "VICTORY":{p:[],u:["Show 'Victorious' window and end game"]},
  "DEFEAT":{p:[],u:["Show 'Defeated' window and end game"]},
  "RESIZE_VIEW_GUARDBAND":{p:["REAL","REAL"],u:["Allow bigger objects to be perceived as onscreen near the edge (",",",") Width then height, in world units."]},
  "DELETE_ALL_UNMANNED":{p:[],u:["Delete all unmanned (sniped) vehicles."]},
  "CHOOSE_VICTIM_ALWAYS_USES_NORMAL":{p:["BOOLEAN"],u:["Force ChooseVictim to ignore game difficulty and always use Normal setting "," (true to enable, false to disable)."]},
  "SET_TRAIN_HELD":{p:["UNIT","BOOLEAN"],u:[" "," sets its held status to "]},
  "NAMED_SET_EVAC_LEFT_OR_RIGHT":{p:["UNIT","LEFT_OR_RIGHT"],u:[" "," will exit its riders on its "]},
  "ENABLE_OBJECT_SOUND":{p:["UNIT"],u:["Enable (or trigger) ","'s ambient sound."]},
  "DISABLE_OBJECT_SOUND":{p:["UNIT"],u:["Disable ","'s ambient sound."]},
  "CONDITION_FALSE":{p:[],u:["False."]},
  "COUNTER":{p:["COUNTER","COMPARISON","INT"],u:["Counter "," IS "," "]},
  "UNIT_HEALTH":{p:["UNIT","COMPARISON","INT"],u:[" "," Health IS "," "," percent."]},
  "FLAG":{p:["FLAG","BOOLEAN"],u:[" "," IS "]},
  "TEAM_STATE_IS":{p:["TEAM","TEAM_STATE"],u:[" "," state IS "]},
  "TEAM_STATE_IS_NOT":{p:["TEAM","TEAM_STATE"],u:[" "," state IS NOT "]},
  "CONDITION_TRUE":{p:[],u:["True."]},
  "TIMER_EXPIRED":{p:["COUNTER"],u:["Timer "," has expired."]},
  "PLAYER_ALL_DESTROYED":{p:["SIDE"],u:["Everything belonging to "," has been destroyed."]},
  "PLAYER_ALL_BUILDFACILITIES_DESTROYED":{p:["SIDE"],u:["All factories belonging to "," have been destroyed."]},
  "TEAM_INSIDE_AREA_PARTIALLY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:[" "," has one or more units in "," (",")."]},
  "NAMED_INSIDE_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," is in "," (",")."]},
  "TEAM_DESTROYED":{p:["TEAM"],u:[" "," has been destroyed."]},
  "NAMED_DESTROYED":{p:["UNIT"],u:[" "," has been destroyed."]},
  "NAMED_DYING":{p:["UNIT"],u:[" "," has been killed, but still on screen."]},
  "NAMED_TOTALLY_DEAD":{p:["UNIT"],u:[" "," has been killed, and is finished dying."]},
  "BRIDGE_BROKEN":{p:["BRIDGE"],u:[" "," has been broken."]},
  "BRIDGE_REPAIRED":{p:["BRIDGE"],u:[" "," has been repaired."]},
  "NAMED_NOT_DESTROYED":{p:["UNIT"],u:[" "," exists and is alive."]},
  "TEAM_HAS_UNITS":{p:["TEAM"],u:[" "," has one or more units."]},
  "CAMERA_MOVEMENT_FINISHED":{p:[],u:["The camera movement has finished."]},
  "NAMED_INSIDE_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," is inside "]},
  "NAMED_OUTSIDE_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," is outside "]},
  "TEAM_INSIDE_AREA_ENTIRELY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:[" "," is all inside "," (",")."]},
  "TEAM_OUTSIDE_AREA_ENTIRELY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:[" "," is completely outside "," (",")."]},
  "NAMED_ATTACKED_BY_OBJECTTYPE":{p:["UNIT","OBJECT_TYPE"],u:[" "," has been attacked by a(n) "]},
  "TEAM_ATTACKED_BY_OBJECTTYPE":{p:["TEAM","OBJECT_TYPE"],u:[" "," has been attacked by a(n) "]},
  "NAMED_ATTACKED_BY_PLAYER":{p:["UNIT","SIDE"],u:[" "," has been attacked by "]},
  "TEAM_ATTACKED_BY_PLAYER":{p:["TEAM","SIDE"],u:[" "," has been attacked by "]},
  "BUILT_BY_PLAYER":{p:["OBJECT_TYPE","SIDE"],u:[" "," has been built by "]},
  "NAMED_CREATED":{p:["UNIT"],u:[" "," has been created."]},
  "TEAM_CREATED":{p:["TEAM"],u:[" "," has been created."]},
  "PLAYER_HAS_CREDITS":{p:["INT","COMPARISON","SIDE"],u:[" "," is "," the number of credits possessed by "]},
  "NAMED_DISCOVERED":{p:["UNIT","SIDE"],u:[" "," has been discovered by "]},
  "NAMED_BUILDING_IS_EMPTY":{p:["UNIT"],u:[" "," is empty."]},
  "BUILDING_ENTERED_BY_PLAYER":{p:["SIDE","UNIT"],u:[" "," has entered building named "]},
  "ENEMY_SIGHTED":{p:["UNIT","RELATION","SIDE"],u:[" "," sees a(n) "," unit belonging to ","."]},
  "TYPE_SIGHTED":{p:["UNIT","OBJECT_TYPE","SIDE"],u:[" "," sees a(n) "," belonging to ","."]},
  "TEAM_DISCOVERED":{p:["TEAM","SIDE"],u:[" "," has been discovered by "]},
  "MISSION_ATTEMPTS":{p:["SIDE","COMPARISON","INT"],u:[" "," has attempted the mission "," "," times."]},
  "NAMED_OWNED_BY_PLAYER":{p:["UNIT","SIDE"],u:[" "," is owned by "]},
  "TEAM_OWNED_BY_PLAYER":{p:["TEAM","SIDE"],u:[" "," is owned by "]},
  "PLAYER_HAS_N_OR_FEWER_BUILDINGS":{p:["SIDE","INT"],u:[" "," currently owns "," or fewer buildings."]},
  "PLAYER_HAS_N_OR_FEWER_FACTION_BUILDINGS":{p:["SIDE","INT"],u:[" "," currently owns "," or fewer faction buildings."]},
  "PLAYER_HAS_POWER":{p:["SIDE"],u:[" "," buildings are powered."]},
  "PLAYER_HAS_NO_POWER":{p:["SIDE"],u:[" "," buildings are not powered."]},
  "NAMED_REACHED_WAYPOINTS_END":{p:["UNIT","WAYPOINT_PATH"],u:[" "," has reached the end of "]},
  "TEAM_REACHED_WAYPOINTS_END":{p:["TEAM","WAYPOINT_PATH"],u:[" "," has reached the end of "]},
  "NAMED_SELECTED":{p:["UNIT"],u:[" "," is currently selected."]},
  "NAMED_ENTERED_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," enters "]},
  "NAMED_EXITED_AREA":{p:["UNIT","TRIGGER_AREA"],u:[" "," exits "]},
  "TEAM_ENTERED_AREA_ENTIRELY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:[" "," all enter "," (",")."]},
  "TEAM_ENTERED_AREA_PARTIALLY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:["One unit from "," enters "," (",")."]},
  "TEAM_EXITED_AREA_ENTIRELY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:[" "," all exit "," (",")."]},
  "TEAM_EXITED_AREA_PARTIALLY":{p:["TEAM","TRIGGER_AREA","SURFACES_ALLOWED"],u:["One unit from "," exits "," (",")."]},
  "MULTIPLAYER_ALLIED_VICTORY":{p:[],u:["The multiplayer game has ended in victory for the local player and his allies."]},
  "MULTIPLAYER_ALLIED_DEFEAT":{p:[],u:["The multiplayer game has ended in defeat for the local player and his allies."]},
  "MULTIPLAYER_PLAYER_DEFEAT":{p:[],u:["Everything belonging to the local player has been destroyed, but his allies may or may not have been defeated."]},
  "HAS_FINISHED_VIDEO":{p:["MOVIE"],u:[" "," has completed playing."]},
  "HAS_FINISHED_SPEECH":{p:["DIALOG"],u:[" "," has completed playing."]},
  "HAS_FINISHED_AUDIO":{p:["SOUND"],u:[" "," has completed playing."]},
  "PLAYER_TRIGGERED_SPECIAL_POWER":{p:["SIDE","SPECIAL_POWER"],u:["Player "," starts using ","."]},
  "PLAYER_TRIGGERED_SPECIAL_POWER_FROM_NAMED":{p:["SIDE","SPECIAL_POWER","UNIT"],u:["Player "," starts using "," from ","."]},
  "PLAYER_MIDWAY_SPECIAL_POWER":{p:["SIDE","SPECIAL_POWER"],u:["Player "," is midway using ","."]},
  "PLAYER_MIDWAY_SPECIAL_POWER_FROM_NAMED":{p:["SIDE","SPECIAL_POWER","UNIT"],u:["Player "," is midway using "," from ","."]},
  "PLAYER_COMPLETED_SPECIAL_POWER":{p:["SIDE","SPECIAL_POWER"],u:["Player "," completed using ","."]},
  "PLAYER_COMPLETED_SPECIAL_POWER_FROM_NAMED":{p:["SIDE","SPECIAL_POWER","UNIT"],u:["Player "," completed using "," from ","."]},
  "PLAYER_ACQUIRED_SCIENCE":{p:["SIDE","SCIENCE"],u:["Player "," acquired ","."]},
  "PLAYER_CAN_PURCHASE_SCIENCE":{p:["SIDE","SCIENCE"],u:["Player "," can purchase ","."]},
  "PLAYER_HAS_SCIENCEPURCHASEPOINTS":{p:["SIDE","INT"],u:["Player "," has at least "," Science Purchase Points available."]},
  "NAMED_HAS_FREE_CONTAINER_SLOTS":{p:["UNIT"],u:[" "," has free container slots."]},
  "PLAYER_BUILT_UPGRADE":{p:["SIDE","UPGRADE"],u:["Player "," built ","."]},
  "PLAYER_BUILT_UPGRADE_FROM_NAMED":{p:["SIDE","UPGRADE","UNIT"],u:["Player "," built "," from ","."]},
  "PLAYER_DESTROYED_N_BUILDINGS_PLAYER":{p:["SIDE","INT","SIDE"],u:["Player "," destroyed "," or more buildings owned by ","."]},
  "PLAYER_HAS_OBJECT_COMPARISON":{p:["SIDE","COMPARISON","INT","OBJECT_TYPE"],u:[" "," has "," "," unit or structure of type "]},
  "PLAYER_HAS_COMPARISON_UNIT_TYPE_IN_TRIGGER_AREA":{p:["SIDE","COMPARISON","INT","OBJECT_TYPE","TRIGGER_AREA"],u:[" "," has "," "," unit or structure of type "," in the "]},
  "PLAYER_HAS_COMPARISON_UNIT_KIND_IN_TRIGGER_AREA":{p:["SIDE","COMPARISON","INT","KIND_OF_PARAM","TRIGGER_AREA"],u:[" "," has "," "," unit or structure with "," in the "]},
  "PLAYER_POWER_COMPARE_PERCENT":{p:["SIDE","COMPARISON","INT"],u:[" "," has "," "," percent power supply ratio."]},
  "PLAYER_EXCESS_POWER_COMPARE_VALUE":{p:["SIDE","COMPARISON","INT"],u:[" "," has "," "," excess kilowatts power supply."]},
  "UNIT_EMPTIED":{p:["UNIT"],u:[" "," emptied its contents."]},
  "SKIRMISH_SPECIAL_POWER_READY":{p:["SIDE","SPECIAL_POWER"],u:[" "," is ready to fire ","."]},
  "UNIT_HAS_OBJECT_STATUS":{p:["UNIT","OBJECT_STATUS"],u:[" "," has "]},
  "TEAM_ALL_HAS_OBJECT_STATUS":{p:["TEAM","OBJECT_STATUS"],u:[" "," has "]},
  "TEAM_SOME_HAVE_OBJECT_STATUS":{p:["TEAM","OBJECT_STATUS"],u:[" "," has "]},
  "SKIRMISH_VALUE_IN_AREA":{p:["SIDE","COMPARISON","INT","TRIGGER_AREA"],u:[" "," has "," "," within area "]},
  "SKIRMISH_PLAYER_FACTION":{p:["SIDE","FACTION_NAME"],u:[" "," is "]},
  "SKIRMISH_SUPPLIES_VALUE_WITHIN_DISTANCE":{p:["SIDE","REAL","TRIGGER_AREA","REAL"],u:[" "," has supplies within "," of "," worth at least "]},
  "SKIRMISH_TECH_BUILDING_WITHIN_DISTANCE":{p:["SIDE","REAL","TRIGGER_AREA"],u:[" "," has a tech building within "," of "]},
  "SKIRMISH_COMMAND_BUTTON_READY_ALL":{p:["SIDE","TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" ","'s "," are ready to use "," (all applicable members)."]},
  "SKIRMISH_COMMAND_BUTTON_READY_PARTIAL":{p:["SIDE","TEAM","COMMANDBUTTON_ALL_ABILITIES"],u:[" ","'s "," are ready to use "," (at least one member)."]},
  "SKIRMISH_UNOWNED_FACTION_UNIT_EXISTS":{p:["SIDE","COMPARISON","INT"],u:[" ",". There are "," "," unowned faction units."]},
  "SKIRMISH_PLAYER_HAS_PREREQUISITE_TO_BUILD":{p:["SIDE","OBJECT_TYPE"],u:[" "," can build ","."]},
  "SKIRMISH_PLAYER_HAS_COMPARISON_GARRISONED":{p:["SIDE","COMPARISON","INT"],u:[" "," has "," "," garrisoned buildings."]},
  "SKIRMISH_PLAYER_HAS_COMPARISON_CAPTURED_UNITS":{p:["SIDE","COMPARISON","INT"],u:[" "," has captured "," "," units."]},
  "SKIRMISH_NAMED_AREA_EXIST":{p:["SIDE","TRIGGER_AREA"],u:[" ",". "," exists."]},
  "SKIRMISH_PLAYER_HAS_UNITS_IN_AREA":{p:["SIDE","TRIGGER_AREA"],u:[" "," has units in ","."]},
  "SKIRMISH_PLAYER_HAS_BEEN_ATTACKED_BY_PLAYER":{p:["SIDE","SIDE"],u:[" "," has been attacked by ","."]},
  "SKIRMISH_PLAYER_IS_OUTSIDE_AREA":{p:["SIDE","TRIGGER_AREA"],u:[" "," doesn't have units in ","."]},
  "SKIRMISH_PLAYER_HAS_DISCOVERED_PLAYER":{p:["SIDE","SIDE"],u:[" "," has discovered ","."]},
  "MUSIC_TRACK_HAS_COMPLETED":{p:["MUSIC","INT"],u:[" "," has completed at least "," times. (NOTE: This can only be used to "]},
  "SUPPLY_SOURCE_SAFE":{p:["SIDE","INT"],u:[" "," closest supply source with at least "," available resources is SAFE from enemy influence."]},
  "SUPPLY_SOURCE_ATTACKED":{p:["SIDE"],u:[" "," supply source is under attack."]},
  "START_POSITION_IS":{p:["SIDE","INT"],u:[" "," starting position is "," ."]},
  "PLAYER_LOST_OBJECT_TYPE":{p:["SIDE","OBJECT_TYPE"],u:[" "," has lost an object of type "," (can be an object type list)."]},
  "SHOW_WEATHER":{p:["BOOLEAN"],u:["Show Weather = "]}
};