// Auto-generated from Scripts.ini + ZH Scripts.h enum
const COND_DATA=[
  {i:"CONDITION_FALSE",t:0,p:["Scripting","False"]},
  {i:"COUNTER",t:1,p:["Scripting","Counter compared to a value"]},
  {i:"UNIT_HEALTH",t:52,p:["Health","Unit health % compared to a value"]},
  {i:"FLAG",t:2,p:["Scripting","Flag compared to a value"]},
  {i:"TEAM_STATE_IS",t:11,p:["Team","State","Team state is"]},
  {i:"TEAM_STATE_IS_NOT",t:12,p:["Team","State","Team state is not"]},
  {i:"CONDITION_TRUE",t:3,p:["Scripting","True"]},
  {i:"TIMER_EXPIRED",t:4,p:["Scripting","Timer expired"]},
  {i:"PLAYER_ALL_DESTROYED",t:5,p:["Player","Destroyed","All units and buildings destroyed"]},
  {i:"PLAYER_ALL_BUILDFACILITIES_DESTROYED",t:6,p:["Player","Destroyed","All factories destroyed"]},
  {i:"TEAM_INSIDE_AREA_PARTIALLY",t:7,p:["Team","Area","Team has units in an area"]},
  {i:"NAMED_INSIDE_AREA",t:13,p:["Unit","Area","Unit entered area"]},
  {i:"TEAM_DESTROYED",t:8,p:["Team","Destroyed","Team is destroyed"]},
  {i:"NAMED_DESTROYED",t:15,p:["Unit","Destroyed","Unit is destroyed"]},
  {i:"NAMED_DYING",t:55,p:["Unit","Destroyed","Unit is dying"]},
  {i:"NAMED_TOTALLY_DEAD",t:56,p:["Unit","Destroyed","Unit is finished dying"]},
  {i:"BRIDGE_BROKEN",t:54,p:["Bridge","Bridge is broken"]},
  {i:"BRIDGE_REPAIRED",t:53,p:["Bridge","Bridge is repaired"]},
  {i:"NAMED_NOT_DESTROYED",t:16,p:["Unit","Exists","Unit exists and is alive"]},
  {i:"TEAM_HAS_UNITS",t:10,p:["Team","Exists","Team has units"]},
  {i:"CAMERA_MOVEMENT_FINISHED",t:9,p:["Camera","Camera movement finished"]},
  {i:"NAMED_OUTSIDE_AREA",t:14,p:["Unit","Area","Unit outside an area"]},
  {i:"TEAM_INSIDE_AREA_ENTIRELY",t:17,p:["Team","Area","Team completely inside an area"]},
  {i:"TEAM_OUTSIDE_AREA_ENTIRELY",t:18,p:["Team","Area","Team is completely outside an area"]},
  {i:"NAMED_ATTACKED_BY_OBJECTTYPE",t:19,p:["Unit","Attacked","Unit is attacked by a specific unit type"]},
  {i:"TEAM_ATTACKED_BY_OBJECTTYPE",t:20,p:["Team","Attacked","Team is attacked by a specific unit type"]},
  {i:"NAMED_ATTACKED_BY_PLAYER",t:21,p:["Unit","Attacked","Unit has been attacked by a player"]},
  {i:"TEAM_ATTACKED_BY_PLAYER",t:22,p:["Team","Attacked","Team has been attacked by a player"]},
  {i:"BUILT_BY_PLAYER",t:23,p:["Player","Owns","Player has built an object type"]},
  {i:"NAMED_CREATED",t:24,p:["Unit","Exists","Unit has been created"]},
  {i:"TEAM_CREATED",t:25,p:["Team","Exists","Team has been created"]},
  {i:"PLAYER_HAS_CREDITS",t:26,p:["Player","Money","Player has (comparison) to a number of credits"]},
  {i:"NAMED_DISCOVERED",t:27,p:["Player","Discovered","Player has discovered a specific unit"]},
  {i:"NAMED_BUILDING_IS_EMPTY",t:77,p:["Unit","Garrisoned","A specific building is empty"]},
  {i:"BUILDING_ENTERED_BY_PLAYER",t:50,p:["Player","Player has entered a specific building"]},
  {i:"ENEMY_SIGHTED",t:51,p:["Unit","Sighted","Unit has sighted a(n) friendly|neutral|enemy unit belonging to a player"]},
  {i:"TYPE_SIGHTED",t:76,p:["Unit","Sighted","Unit has sighted a type of unit belonging to a player"]},
  {i:"TEAM_DISCOVERED",t:28,p:["Player","Discovered","Player has discovered a team"]},
  {i:"NAMED_OWNED_BY_PLAYER",t:30,p:["Player","Owns","Player owns the specific Unit"]},
  {i:"TEAM_OWNED_BY_PLAYER",t:31,p:["Player","Owns","Player owns a specific team"]},
  {i:"PLAYER_HAS_N_OR_FEWER_BUILDINGS",t:32,p:["Player","Owns","Player currently owns N or fewer buildings"]},
  {i:"PLAYER_HAS_N_OR_FEWER_FACTION_BUILDINGS",t:78,p:["Player","Owns","Player currently owns N or fewer faction buildings"]},
  {i:"PLAYER_HAS_POWER",t:33,p:["Player","Power","Player's base currently has power"]},
  {i:"PLAYER_HAS_NO_POWER",t:46,p:["Player","Power","Player's base currently has no power"]},
  {i:"NAMED_REACHED_WAYPOINTS_END",t:34,p:["Path","Unit has reached the end of a specific waypoint path"]},
  {i:"TEAM_REACHED_WAYPOINTS_END",t:35,p:["Path","Team has reached the end of a specific waypoint path"]},
  {i:"NAMED_SELECTED",t:36,p:["Selected","Unit currently selected"]},
  {i:"NAMED_ENTERED_AREA",t:37,p:["Unit","Area","Unit enters an area"]},
  {i:"NAMED_EXITED_AREA",t:38,p:["Unit","Area","Unit exits an area"]},
  {i:"TEAM_ENTERED_AREA_ENTIRELY",t:39,p:["Team","Area","Team entirely enters an area"]},
  {i:"TEAM_ENTERED_AREA_PARTIALLY",t:40,p:["Team","Area","One unit enters an area"]},
  {i:"TEAM_EXITED_AREA_ENTIRELY",t:41,p:["Team","Area","Team entirely exits an area"]},
  {i:"TEAM_EXITED_AREA_PARTIALLY",t:42,p:["Team","Area","One unit exits an area"]},
  {i:"MULTIPLAYER_ALLIED_VICTORY",t:43,p:["Multiplayer Victory & Defeat","Multiplayer allied victory"]},
  {i:"MULTIPLAYER_ALLIED_DEFEAT",t:44,p:["Multiplayer Victory & Defeat","Multiplayer allied defeat"]},
  {i:"MULTIPLAYER_PLAYER_DEFEAT",t:45,p:["Multiplayer Victory & Defeat","Multiplayer local player defeat check"]},
  {i:"HAS_FINISHED_VIDEO",t:47,p:["Multimedia","Finished","(UNUSED)Video has completed playing"]},
  {i:"HAS_FINISHED_SPEECH",t:48,p:["Multimedia","Finished","Speech has completed playing"]},
  {i:"HAS_FINISHED_AUDIO",t:49,p:["Multimedia","Finished","Sound has completed playing"]},
  {i:"PLAYER_TRIGGERED_SPECIAL_POWER",t:60,p:["Player","Special Power","Player starts using a special power"]},
  {i:"PLAYER_COMPLETED_SPECIAL_POWER",t:61,p:["Player","Special Power","Player completed using a special power"]},
  {i:"PLAYER_ACQUIRED_SCIENCE",t:100,p:["Player","Science","Player acquired a Science"]},
  {i:"NAMED_HAS_FREE_CONTAINER_SLOTS",t:108,p:["Unit","Container","Container has free container slots"]},
  {i:"PLAYER_BUILT_UPGRADE",t:68,p:["Player","Upgrades","Player built an upgrade"]},
  {i:"PLAYER_DESTROYED_N_BUILDINGS_PLAYER",t:70,p:["Player","Destroyed","Player destroyed N or more of an opponent's buildings"]},
  {i:"PLAYER_HAS_OBJECT_COMPARISON",t:57,p:["Player","Owns","Player has (comparison) unit type"]},
  {i:"PLAYER_HAS_COMPARISON_UNIT_TYPE_IN_TRIGGER_AREA",t:73,p:["Player","Area","Player has (comparison) unit type in an area"]},
  {i:"PLAYER_HAS_COMPARISON_UNIT_KIND_IN_TRIGGER_AREA",t:74,p:["Player","Owns","Player has (comparison) kind of unit or structure in an area"]},
  {i:"PLAYER_POWER_COMPARE_PERCENT",t:82,p:["Player","Power","Player has (comparison) percent power supply to consumption"]},
  {i:"PLAYER_EXCESS_POWER_COMPARE_VALUE",t:83,p:["Player","Power","Player has (comparison) kilowatts excess power supply"]},
  {i:"UNIT_EMPTIED",t:75,p:["Unit","Container","Container has emptied its contents"]},
  {i:"SKIRMISH_SPECIAL_POWER_READY",t:84,p:["Player","Special Power","Player's special power is ready to fire"]},
  {i:"UNIT_HAS_OBJECT_STATUS",t:79,p:["Status","Unit","Unit has object status"]},
  {i:"TEAM_SOME_HAVE_OBJECT_STATUS",t:81,p:["Status","Team","Team has object status - partial"]},
  {i:"SKIRMISH_VALUE_IN_AREA",t:85,p:["Player","Area","Player has total value in area"]},
  {i:"SKIRMISH_PLAYER_FACTION",t:86,p:["Skirmish","Player","Player is faction"]},
  {i:"SKIRMISH_SUPPLIES_VALUE_WITHIN_DISTANCE",t:87,p:["Skirmish Only","Supplies are within specified distance"]},
  {i:"SKIRMISH_TECH_BUILDING_WITHIN_DISTANCE",t:88,p:["Skirmish Only","Tech building is within specified distance"]},
  {i:"SKIRMISH_UNOWNED_FACTION_UNIT_EXISTS",t:91,p:["Skirmish","Unowned faction unit -- comparison"]},
  {i:"SKIRMISH_PLAYER_HAS_COMPARISON_GARRISONED",t:93,p:["Skirmish","Player","Player has garrisoned buildings -- comparison"]},
  {i:"SKIRMISH_PLAYER_HAS_UNITS_IN_AREA",t:96,p:["Player","Area","Player has units in an area"]},
  {i:"SKIRMISH_PLAYER_HAS_BEEN_ATTACKED_BY_PLAYER",t:97,p:["Player","Player has been attacked by player"]},
  {i:"SKIRMISH_PLAYER_IS_OUTSIDE_AREA",t:98,p:["Player","Area","Player doesn't have units in an area"]},
  {i:"MUSIC_TRACK_HAS_COMPLETED",t:103,p:["Multimedia","Finished","Music track has completed some number of times"]},
  {i:"SUPPLY_SOURCE_SAFE",t:105,p:["Skirmish","Supply Source","Supply source is safe"]},
  {i:"SUPPLY_SOURCE_ATTACKED",t:106,p:["Skirmish","Supply Source","Supply source is attacked"]},
  {i:"START_POSITION_IS",t:107,p:["Skirmish","Start position"]},
  {i:"PLAYER_LOST_OBJECT_TYPE",t:104,p:["Player","Destroyed","Player has lost an object of type"]}
];
const ACT_DATA=[
  {i:"DEBUG_MESSAGE_BOX",t:0,p:["Scripting","Debug","Display message and pause"]},
  {i:"DEBUG_STRING",t:101,p:["Scripting","Debug","Display string"]},
  {i:"DEBUG_CRASH_BOX",t:216,p:["Scripting","Debug","Display a crash box (debug and internal builds only)"]},
  {i:"SET_FLAG",t:1,p:["Scripting","Flags","Set flag to value"]},
  {i:"SET_COUNTER",t:2,p:["Scripting","Counters","Set counter to a value"]},
  {i:"SET_INFANTRY_LIGHTING_OVERRIDE",t:324,p:["Map","Environment","Infantry Lighting - Set"]},
  {i:"RESET_INFANTRY_LIGHTING_OVERRIDE",t:325,p:["Map","Environment","Infantry Lighting - Reset"]},
  {i:"VICTORY",t:3,p:["User","Announce win"]},
  {i:"DEFEAT",t:4,p:["User","Announce lose"]},
  {i:"NO_OP",t:5,p:["Scripting","Debug","Null operation"]},
  {i:"SET_TIMER",t:6,p:["Scripting","Timer","Frame countdown timer -- set"]},
  {i:"SET_RANDOM_TIMER",t:147,p:["Scripting","Timer","Frame countdown timer -- set random"]},
  {i:"STOP_TIMER",t:149,p:["Scripting","Timer","Timer -- stop"]},
  {i:"RESTART_TIMER",t:150,p:["Scripting","Timer","Timer -- restart stopped"]},
  {i:"PLAY_SOUND_EFFECT",t:7,p:["Multimedia","Sound Effect","Play sound effect"]},
  {i:"ENABLE_SCRIPT",t:8,p:["Scripting","Script","Enable Script"]},
  {i:"DISABLE_SCRIPT",t:9,p:["Scripting","Script","Disable script"]},
  {i:"CALL_SUBROUTINE",t:10,p:["Scripting","Script","Run subroutine script"]},
  {i:"PLAY_SOUND_EFFECT_AT",t:11,p:["Multimedia","Sound Effect","Play sound effect at waypoint"]},
  {i:"DAMAGE_MEMBERS_OF_TEAM",t:12,p:["Team","Damage or Remove","Damage the members of a team"]},
  {i:"MOVE_TEAM_TO",t:13,p:["Team","Move","Set to move to a location"]},
  {i:"TEAM_FOLLOW_WAYPOINTS",t:36,p:["Team","Move","Set to follow a waypoint path"]},
  {i:"TEAM_FOLLOW_WAYPOINTS_EXACT",t:281,p:["Team","Move","Set to EXACTLY follow a waypoint path"]},
  {i:"TEAM_WANDER_IN_PLACE",t:233,p:["Team","Move","Set to wander around current location"]},
  {i:"TEAM_INCREASE_PRIORITY",t:234,p:["Team","AI","Increase priority by Success Priority Increase amount"]},
  {i:"TEAM_DECREASE_PRIORITY",t:235,p:["Team","AI","Reduce priority by Failure Priority Decrease amount"]},
  {i:"TEAM_WANDER",t:112,p:["Team","Move","Set to follow a waypoint path -- wander"]},
  {i:"TEAM_PANIC",t:113,p:["Team","Move","Set to follow a waypoint path -- panic"]},
  {i:"MOVE_NAMED_UNIT_TO",t:38,p:["Unit","Move","Move a specific unit to a location"]},
  {i:"TEAM_SET_STATE",t:37,p:["Scripting","Misc","Team custom state - set state"]},
  {i:"CREATE_REINFORCEMENT_TEAM",t:34,p:["Team","Create","Spawn a reinforcement team"]},
  {i:"SKIRMISH_BUILD_BUILDING",t:244,p:["Skirmish Only","Build","Build a building"]},
  {i:"AI_PLAYER_BUILD_SUPPLY_CENTER",t:285,p:["Player","AI","AI player build near a supply source"]},
  {i:"AI_PLAYER_BUILD_TYPE_NEAREST_TEAM",t:-1,p:["Player","AI","AI player build nearest specified team"]},
  {i:"TEAM_GUARD_SUPPLY_CENTER",t:312,p:["Team","Guard","Set to guard a supply source"]},
  {i:"AI_PLAYER_BUILD_UPGRADE",t:286,p:["Player","AI","AI player build an upgrade"]},
  {i:"SKIRMISH_FOLLOW_APPROACH_PATH",t:245,p:["Skirmish Only","Move","Team follow approach path"]},
  {i:"SKIRMISH_MOVE_TO_APPROACH_PATH",t:249,p:["Skirmish Only","Move","Team move to approach path"]},
  {i:"SKIRMISH_BUILD_BASE_DEFENSE_FRONT",t:250,p:["Skirmish Only","Build","Build base defense on front perimeter"]},
  {i:"SKIRMISH_BUILD_BASE_DEFENSE_FLANK",t:254,p:["Skirmish Only","Build","Build base defense on flank perimeter"]},
  {i:"SKIRMISH_BUILD_STRUCTURE_FRONT",t:255,p:["Skirmish Only","Build","Build structure on front perimeter"]},
  {i:"SKIRMISH_BUILD_STRUCTURE_FLANK",t:256,p:["Skirmish Only","Build","Build structure on flank perimeter"]},
  {i:"RECRUIT_TEAM",t:177,p:["Team","Create","Recruit a team"]},
  {i:"MOVE_CAMERA_TO",t:14,p:["Camera","Move","Move the camera to a location"]},
  {i:"ZOOM_CAMERA",t:117,p:["Camera","Adjust","Change the camera zoom"]},
  {i:"CAMERA_FADE_ADD",t:121,p:["Camera","Camera FX","Fade using an add blend to white"]},
  {i:"CAMERA_FADE_SUBTRACT",t:122,p:["Camera","Camera FX","Fade using a subtractive blend to black"]},
  {i:"CAMERA_FADE_MULTIPLY",t:124,p:["Camera","Camera FX","Fade using a multiply blend to black"]},
  {i:"CAMERA_FADE_SATURATE",t:123,p:["Camera","Camera FX","Fade using a saturate blend"]},
  {i:"PITCH_CAMERA",t:118,p:["Camera","Adjust","Change the camera pitch"]},
  {i:"CAMERA_FOLLOW_NAMED",t:119,p:["Camera","Follow","Start following a specific unit"]},
  {i:"CAMERA_STOP_FOLLOW",t:132,p:["Camera","Follow","Stop following any units"]},
  {i:"SETUP_CAMERA",t:114,p:["Camera","Adjust","Set up the camera"]},
  {i:"INCREMENT_COUNTER",t:15,p:["Scripting","Counters","Increment counter"]},
  {i:"DECREMENT_COUNTER",t:16,p:["Scripting","Counters","Decrement counter"]},
  {i:"MOVE_CAMERA_ALONG_WAYPOINT_PATH",t:17,p:["Camera","Move","Move along a waypoint path"]},
  {i:"ROTATE_CAMERA",t:18,p:["Camera","Rotate","Rotate around the current viewpoint"]},
  {i:"RESET_CAMERA",t:19,p:["Camera","Move","Reset to the default view"]},
  {i:"SET_MILLISECOND_TIMER",t:20,p:["Scripting","Timer","Seconds countdown timer -- set"]},
  {i:"SET_RANDOM_MSEC_TIMER",t:148,p:["Scripting","Timer","Seconds countdown timer -- set random"]},
  {i:"ADD_TO_MSEC_TIMER",t:151,p:["Scripting","Timer","Seconds countdown timer -- add seconds"]},
  {i:"SUB_FROM_MSEC_TIMER",t:152,p:["Scripting","Timer","Seconds countdown timer -- subtract seconds"]},
  {i:"CAMERA_MOD_FREEZE_TIME",t:21,p:["Camera","Move","Modify","Freeze time during the camera movement"]},
  {i:"SUSPEND_BACKGROUND_SOUNDS",t:24,p:["Multimedia","All Sounds","Suspend all sounds"]},
  {i:"RESUME_BACKGROUND_SOUNDS",t:25,p:["Multimedia","All Sounds","Resume all sounds"]},
  {i:"CAMERA_MOD_SET_FINAL_ZOOM",t:26,p:["Camera","Move","Modify","Set Final zoom for camera movement"]},
  {i:"CAMERA_MOD_SET_FINAL_PITCH",t:27,p:["Camera","Move","Modify","Set Final pitch for camera movement"]},
  {i:"CAMERA_MOD_LOOK_TOWARD",t:32,p:["Camera","Modify","Move","Camera look toward point while moving"]},
  {i:"CREATE_OBJECT",t:23,p:["Unit","Spawn","Spawn unit"]},
  {i:"TEAM_ATTACK_TEAM",t:33,p:["Team","Attack","Set to attack -- another team"]},
  {i:"NAMED_ATTACK_NAMED",t:39,p:["Unit","Attack","Set unit to attack another unit"]},
  {i:"CREATE_NAMED_ON_TEAM_AT_WAYPOINT",t:40,p:["Unit","Spawn","Spawn -- named unit on a team at a waypoint"]},
  {i:"CREATE_UNNAMED_ON_TEAM_AT_WAYPOINT",t:41,p:["Unit","Spawn","Spawn -- unnamed unit on a team at a waypoint"]},
  {i:"NAMED_APPLY_ATTACK_PRIORITY_SET",t:42,p:["AttackPrioritySet","ApplySet","Apply unit's attack priority set"]},
  {i:"TEAM_APPLY_ATTACK_PRIORITY_SET",t:43,p:["AttackPrioritySet","ApplySet","Apply a team's attack priority set"]},
  {i:"SET_ATTACK_PRIORITY_THING",t:129,p:["AttackPrioritySet","CreateSet","Modify a set's priority for a single unit type"]},
  {i:"SET_ATTACK_PRIORITY_KIND_OF",t:130,p:["AttackPrioritySet","CreateSet","Modify a set's priorities for all of a kind"]},
  {i:"SET_DEFAULT_ATTACK_PRIORITY",t:131,p:["AttackPrioritySet","CreateSet","Specify the set's default priority"]},
  {i:"PLAYER_ADD_RANKLEVEL",t:273,p:["Player","Experience","Add or Subtract Rank Levels"]},
  {i:"PLAYER_SET_RANKLEVEL",t:274,p:["Player","Experience","Set Rank Level"]},
  {i:"PLAYER_SET_RANKLEVELLIMIT",t:275,p:["Map","Experience","Set Rank Level Limit for current Map"]},
  {i:"PLAYER_GRANT_SCIENCE",t:276,p:["Player","Science","Grant a Science to a given Player (ignoring prerequisites)"]},
  {i:"PLAYER_SCIENCE_AVAILABILITY",t:298,p:["Player","Science","Set science availability"]},
  {i:"SET_BASE_CONSTRUCTION_SPEED",t:44,p:["Player","AI","Set the delay between building AI teams"]},
  {i:"NAMED_SET_ATTITUDE",t:45,p:["Unit","Mood","Set the general attitude of a specific unit"]},
  {i:"TEAM_SET_ATTITUDE",t:46,p:["Team","Mood","Set the general attitude of a team"]},
  {i:"NAMED_SET_REPULSOR",t:231,p:["Unit","Internal","Repulsor","Set the REPULSOR flag of a specific unit"]},
  {i:"TEAM_SET_REPULSOR",t:232,p:["Team","Internal","Repulsor","Set the REPULSOR flag of a team"]},
  {i:"NAMED_ATTACK_AREA",t:47,p:["Unit","Attack","Set a specific unit to attack a specific trigger area"]},
  {i:"NAMED_ATTACK_TEAM",t:48,p:["Unit","Attack","Set a specific unit to attack a team"]},
  {i:"TEAM_ATTACK_AREA",t:49,p:["Team","Attack","Set to attack -- trigger area"]},
  {i:"TEAM_ATTACK_NAMED",t:50,p:["Team","Attack","Set to attack -- specific unit"]},
  {i:"TEAM_LOAD_TRANSPORTS",t:51,p:["Team","Transport","Transport -- automatically load"]},
  {i:"NAMED_ENTER_NAMED",t:52,p:["Unit","Transport","Transport -- load unit into specific"]},
  {i:"TEAM_ENTER_NAMED",t:53,p:["Team","Transport","Transport -- load team into specific"]},
  {i:"NAMED_EXIT_ALL",t:54,p:["Unit","Transport","Transport -- unload units from specific"]},
  {i:"TEAM_EXIT_ALL",t:55,p:["Team","Transport","Transport -- unload team from all"]},
  {i:"NAMED_FOLLOW_WAYPOINTS",t:56,p:["Unit","Move","Set a specific unit to follow a waypoint path"]},
  {i:"NAMED_FOLLOW_WAYPOINTS_EXACT",t:282,p:["Unit","Move","Set a specific unit to EXACTLY follow a waypoint path"]},
  {i:"NAMED_GUARD",t:57,p:["Unit","Move","Set to guard"]},
  {i:"TEAM_GUARD",t:58,p:["Team","Guard","Set to guard -- current location"]},
  {i:"TEAM_GUARD_POSITION",t:202,p:["Team","Guard","Set to guard -- location"]},
  {i:"TEAM_GUARD_OBJECT",t:203,p:["Team","Guard","Set to guard -- specific unit"]},
  {i:"TEAM_GUARD_AREA",t:204,p:["Team","Guard","Set to guard -- area"]},
  {i:"NAMED_HUNT",t:59,p:["Unit","Hunt","Set a specific unit to hunt"]},
  {i:"TEAM_HUNT_WITH_COMMAND_BUTTON",t:278,p:["Team","Hunt","Set to hunt using commandbutton ability"]},
  {i:"TEAM_HUNT",t:60,p:["Team","Hunt","Set to hunt"]},
  {i:"PLAYER_HUNT",t:96,p:["Player","Hunt","Set all of a player's units to hunt"]},
  {i:"PLAYER_SELL_EVERYTHING",t:61,p:["Player","Set","Set a player to sell everything"]},
  {i:"PLAYER_DISABLE_BASE_CONSTRUCTION",t:62,p:["Player","Build","Set a player to be unable to build buildings"]},
  {i:"PLAYER_DISABLE_UNIT_CONSTRUCTION",t:64,p:["Player","Build","Set a player to be unable to build units"]},
  {i:"PLAYER_ENABLE_BASE_CONSTRUCTION",t:65,p:["Player","Build","Set a player to be able to build buildings"]},
  {i:"PLAYER_ENABLE_UNIT_CONSTRUCTION",t:67,p:["Player","Build","Set a player to be able to build units"]},
  {i:"OVERSIZE_TERRAIN",t:120,p:["Camera","Terrain","Oversize the terrain"]},
  {i:"BUILD_TEAM",t:69,p:["Team","AI","Start building a team"]},
  {i:"NAMED_DAMAGE",t:70,p:["Unit","Damage","Deal damage to a specific unit"]},
  {i:"NAMED_DELETE",t:71,p:["Unit","Damage or Remove","Delete a specific unit"]},
  {i:"TEAM_DELETE",t:72,p:["Team","Damage or Remove","Delete a team"]},
  {i:"TEAM_DELETE_LIVING",t:326,p:["Team","Damage or Remove","Delete a team, but ignore dead guys"]},
  {i:"NAMED_KILL",t:73,p:["Unit","Damage or Remove","Kill a specific unit"]},
  {i:"TEAM_KILL",t:74,p:["Team","Damage or Remove","Kill an entire team"]},
  {i:"PLAYER_KILL",t:75,p:["Player","Damage or Remove","Kill a player"]},
  {i:"CAMEO_FLASH",t:77,p:["User","Flash","Flash a cameo for a specified amount of time"]},
  {i:"NAMED_FLASH",t:78,p:["User","Flash","Flash a specific unit for a specified amount of time"]},
  {i:"TEAM_FLASH",t:79,p:["User","Flash","Flash a team for a specified amount of time"]},
  {i:"NAMED_CUSTOM_COLOR",t:248,p:["User","Flash","Set a specific unit to use a special indicator color"]},
  {i:"NAMED_FLASH_WHITE",t:242,p:["User","Flash","Flash a specific unit white for a specified amount of time"]},
  {i:"INGAME_POPUP_MESSAGE",t:223,p:["User","String","Display Popup Message Box"]},
  {i:"SOUND_PLAY_NAMED",t:82,p:["Multimedia","Sound Effect","Play a sound as though coming from a specific unit"]},
  {i:"SPEECH_PLAY",t:83,p:["Multimedia","Sound Effect","Play a speech file"]},
  {i:"PLAYER_TRANSFER_OWNERSHIP_PLAYER",t:84,p:["Player","Transfer","Transfer assets from one player to another player"]},
  {i:"NAMED_TRANSFER_OWNERSHIP_PLAYER",t:85,p:["Player","Transfer","Transfer a specific unit to the control of a player"]},
  {i:"PLAYER_EXCLUDE_FROM_SCORE_SCREEN",t:311,p:["Player","Score","Exclude this player from the score screen"]},
  {i:"ENABLE_SCORING",t:313,p:["Player","Score","Turn on scoring"]},
  {i:"DISABLE_SCORING",t:314,p:["Player","Score","Turn off scoring"]},
  {i:"PLAYER_RELATES_PLAYER",t:86,p:["Player","Alliances","Change how a player relates to another player"]},
  {i:"RADAR_CREATE_EVENT",t:87,p:["Radar","Create Event","Create a radar event at a specified location"]},
  {i:"OBJECT_CREATE_RADAR_EVENT",t:213,p:["Radar","Create Event","Create  a radar event at a specific object"]},
  {i:"TEAM_CREATE_RADAR_EVENT",t:214,p:["Radar","Create Event","Create  a radar event at a specific team"]},
  {i:"RADAR_ENABLE",t:89,p:["Radar","Control","Enable the radar"]},
  {i:"NAMED_SET_STEALTH_ENABLED",t:291,p:["Unit","Status","Stealth set enabled or disabled"]},
  {i:"TEAM_SET_STEALTH_ENABLED",t:292,p:["Team","Status","Stealth set enabled or disabled"]},
  {i:"NAMED_SET_UNMANNED_STATUS",t:-1,p:["Unit","Status","Make unmanned"]},
  {i:"TEAM_SET_UNMANNED_STATUS",t:-1,p:["Team","Status","Make unmanned"]},
  {i:"NAMED_SET_BOOBYTRAPPED",t:-1,p:["Unit","Status","Make boobytrapped"]},
  {i:"TEAM_SET_BOOBYTRAPPED",t:-1,p:["Team","Status","Make boobytrapped"]},
  {i:"MAP_REVEAL_AT_WAYPOINT",t:90,p:["Map","Shroud or Reveal","Reveal map at waypoint -- fog"]},
  {i:"MAP_SHROUD_AT_WAYPOINT",t:145,p:["Map","Shroud or Reveal","Shroud map at waypoint -- add fog"]},
  {i:"MAP_REVEAL_ALL",t:102,p:["Map","Shroud or Reveal","Reveal the entire map for a player"]},
  {i:"MAP_REVEAL_ALL_PERM",t:229,p:["Map","Shroud or Reveal","Reveal the entire map permanently for a player"]},
  {i:"MAP_REVEAL_ALL_UNDO_PERM",t:230,p:["Map","Shroud or Reveal","Un-Reveal the entire map permanently for a player"]},
  {i:"MAP_SHROUD_ALL",t:146,p:["Map","Shroud or Reveal","Shroud the entire map for a player"]},
  {i:"DISABLE_BORDER_SHROUD",t:317,p:["Map","Shroud or Reveal","Border Shroud is turned off"]},
  {i:"ENABLE_BORDER_SHROUD",t:318,p:["Map","Shroud or Reveal","Border Shroud is turned on"]},
  {i:"TEAM_GARRISON_SPECIFIC_BUILDING",t:103,p:["Team","Garrison","Garrison a specific building with a team"]},
  {i:"EXIT_SPECIFIC_BUILDING",t:104,p:["Unit","Garrison","Empty a specific building"]},
  {i:"TEAM_GARRISON_NEAREST_BUILDING",t:105,p:["Team","Garrison","Garrison a nearby building with a team"]},
  {i:"TEAM_EXIT_ALL_BUILDINGS",t:106,p:["Team","Garrison","Exit all buildings a team is in"]},
  {i:"NAMED_GARRISON_SPECIFIC_BUILDING",t:107,p:["Unit","Garrison","Garrison a specific building with a specific unit"]},
  {i:"NAMED_GARRISON_NEAREST_BUILDING",t:108,p:["Unit","Garrison","Garrison a nearby building with a specific unit"]},
  {i:"NAMED_EXIT_BUILDING",t:109,p:["Unit","Garrison","Exit the building the unit is in"]},
  {i:"PLAYER_EXIT_ALL_BUILDINGS",t:111,p:["Player","Garrison","All units leave their garrisons"]},
  {i:"TEAM_AVAILABLE_FOR_RECRUITMENT",t:91,p:["Team","AI","Set whether members of a team can be recruited into another team"]},
  {i:"TEAM_MERGE_INTO_TEAM",t:93,p:["Team","Merge","Merge a team into another team"]},
  {i:"IDLE_ALL_UNITS",t:246,p:["Scripting","Idle or Restart","Idle all units for all players"]},
  {i:"DISABLE_INPUT",t:94,p:["User","Input","User input -- disable"]},
  {i:"ENABLE_INPUT",t:95,p:["User","Input","User input -- enable"]},
  {i:"SOUND_AMBIENT_PAUSE",t:97,p:["Multimedia","SoundEffects","Pause the ambient sounds"]},
  {i:"SOUND_AMBIENT_RESUME",t:98,p:["Multimedia","SoundEffects","Resume the ambient sounds"]},
  {i:"ENABLE_OBJECT_SOUND",t:-1,p:["Multimedia","Sound Effect","Enable object's ambient sound"]},
  {i:"DISABLE_OBJECT_SOUND",t:-1,p:["Multimedia","Sound Effect","Disable object's ambient sound"]},
  {i:"MUSIC_SET_TRACK",t:99,p:["Multimedia","Music","Play a music track"]},
  {i:"CAMERA_LETTERBOX_BEGIN",t:115,p:["Camera","Letterbox","Begin letterbox mode"]},
  {i:"CAMERA_LETTERBOX_END",t:116,p:["Camera","Letterbox","End letterbox mode"]},
  {i:"CAMERA_BW_MODE_BEGIN",t:125,p:["Camera","Camera FX","Start black & white mode"]},
  {i:"CAMERA_BW_MODE_END",t:126,p:["Camera","Camera FX","Stop black & white mode"]},
  {i:"CAMERA_MOTION_BLUR_JUMP",t:134,p:["Camera","Camera FX","Motion blur zoom with jump cut"]},
  {i:"DRAW_SKYBOX_BEGIN",t:127,p:["Camera","Skybox","Start skybox mode"]},
  {i:"DRAW_SKYBOX_END",t:128,p:["Camera","Skybox","Stop skybox mode"]},
  {i:"FREEZE_TIME",t:137,p:["Scripting","Time","Freeze time"]},
  {i:"UNFREEZE_TIME",t:138,p:["Scripting","Time","Unfreeze time"]},
  {i:"SHOW_MILITARY_CAPTION",t:139,p:["Scripting","Briefing","Show military briefing caption"]},
  {i:"NAMED_SET_HELD",t:225,p:["Unit","Move","Set unit to be held in place, ignoring Physics, Locomotors, etc"]},
  {i:"NAMED_SET_STOPPING_DISTANCE",t:142,p:["Unit","Move","Set stopping distance for current locomotor"]},
  {i:"SET_STOPPING_DISTANCE",t:141,p:["Team","Move","Set stopping distance for each unit's current locomotor"]},
  {i:"SET_FPS_LIMIT",t:143,p:["Scripting","Set max frames per second"]},
  {i:"DISABLE_SPECIAL_POWER_DISPLAY",t:156,p:["Scripting","Special power countdown display -- disable"]},
  {i:"ENABLE_SPECIAL_POWER_DISPLAY",t:157,p:["Scripting","Special power countdown display -- enable"]},
  {i:"NAMED_HIDE_SPECIAL_POWER_DISPLAY",t:158,p:["Unit","Special Power","Special power countdown timer -- hide"]},
  {i:"NAMED_SHOW_SPECIAL_POWER_DISPLAY",t:159,p:["Unit","Special Power","Special power countdown timer -- display"]},
  {i:"MUSIC_SET_VOLUME",t:144,p:["Multimedia","Set the current music volume"]},
  {i:"TEAM_TRANSFER_TO_PLAYER",t:153,p:["Team","Transfer control of a team to a player"]},
  {i:"PLAYER_SET_MONEY",t:154,p:["Player","Set","Set player's money"]},
  {i:"PLAYER_GIVE_MONEY",t:155,p:["Player","Set","Gives or takes from player's money"]},
  {i:"DISPLAY_COUNTER",t:236,p:["Scripting","Counters","Display an individual counter to the user"]},
  {i:"HIDE_COUNTER",t:237,p:["Scripting","Counters","Hide an individual counter from the user"]},
  {i:"DISPLAY_COUNTDOWN_TIMER",t:160,p:["Scripting","Timer","Display an individual timer to the user"]},
  {i:"HIDE_COUNTDOWN_TIMER",t:161,p:["Scripting","Timer","Hides an individual timer from the user"]},
  {i:"DISABLE_COUNTDOWN_TIMER_DISPLAY",t:163,p:["Scripting","Timer","Hide all timers from the user"]},
  {i:"NAMED_STOP_SPECIAL_POWER_COUNTDOWN",t:164,p:["Unit","Special power","Countdown timer -- pause"]},
  {i:"NAMED_START_SPECIAL_POWER_COUNTDOWN",t:165,p:["Unit","Special power","Countdown timer -- resume"]},
  {i:"NAMED_SET_SPECIAL_POWER_COUNTDOWN",t:166,p:["Unit","Special power","Countdown timer -- set"]},
  {i:"SKIRMISH_FIRE_SPECIAL_POWER_AT_MOST_COST",t:251,p:["Player","Special power","Special power -- fire at enemy's highest cost area"]},
  {i:"PLAYER_REPAIR_NAMED_STRUCTURE",t:253,p:["Player","Repair named bridge or structure"]},
  {i:"NAMED_FIRE_SPECIAL_POWER_AT_WAYPOINT",t:168,p:["Unit","Special power","Special Power -- fire at location"]},
  {i:"REFRESH_RADAR",t:170,p:["Radar","Refresh radar terrain"]},
  {i:"NAMED_STOP",t:174,p:["Unit","Set a specific unit to stop"]},
  {i:"TEAM_STOP",t:175,p:["Team","Stop","Have team stop"]},
  {i:"TEAM_STOP_AND_DISBAND",t:176,p:["Team","Stop","Have team stop, then disband"]},
  {i:"TEAM_SET_OVERRIDE_RELATION_TO_TEAM",t:178,p:["Team","Alliance","Override a team's relationship to another team"]},
  {i:"TEAM_REMOVE_OVERRIDE_RELATION_TO_TEAM",t:179,p:["Team","Alliance","Remove an override to a team's relationship to another team"]},
  {i:"TEAM_REMOVE_ALL_OVERRIDE_RELATIONS",t:180,p:["Team","Alliance","Remove all overrides to team's relationship to teams and","or players"]},
  {i:"CAMERA_TETHER_NAMED",t:171,p:["Camera","Follow","Begin tether camera to a specific unit"]},
  {i:"CAMERA_STOP_TETHER_NAMED",t:172,p:["Camera","Follow","End tether to any units"]},
  {i:"CAMERA_LOOK_TOWARD_OBJECT",t:181,p:["Camera","Rotate","Rotate toward unit"]},
  {i:"CAMERA_LOOK_TOWARD_WAYPOINT",t:206,p:["Camera","Rotate","Rotate to look at a waypoint"]},
  {i:"UNIT_DESTROY_ALL_CONTAINED",t:207,p:["Unit","Damage or Remove","Kill all units contained within a specific transport or structure"]},
  {i:"TEAM_SET_OVERRIDE_RELATION_TO_PLAYER",t:183,p:["Team","Override a team's relationship to another player"]},
  {i:"PLAYER_SET_OVERRIDE_RELATION_TO_TEAM",t:185,p:["Player","Alliances","Override a player's relationship to another team"]},
  {i:"TEAM_EXECUTE_SEQUENTIAL_SCRIPT",t:190,p:["Team","SequentialScript","Execute script sequentially -- start"]},
  {i:"TEAM_EXECUTE_SEQUENTIAL_SCRIPT_LOOPING",t:191,p:["Team","SequentialScript","Execute script sequentially -- looping"]},
  {i:"TEAM_STOP_SEQUENTIAL_SCRIPT",t:192,p:["Team","SequentialScript","Execute script sequentially -- stop"]},
  {i:"UNIT_IDLE_FOR_FRAMECOUNT",t:194,p:["Unit","Set to idle for some number of frames"]},
  {i:"TEAM_GUARD_FOR_FRAMECOUNT",t:195,p:["Team","SequentialScript","Set to guard -- number of frames"]},
  {i:"TEAM_IDLE_FOR_FRAMECOUNT",t:196,p:["Team","SequentialScript","Set to idle for some number of frames"]},
  {i:"WATER_CHANGE_HEIGHT",t:197,p:["Map","Modify","Adjust water height to a new level"]},
  {i:"WATER_CHANGE_HEIGHT_OVER_TIME",t:200,p:["Map","Modify","Adjust water height to a new level with damage over time"]},
  {i:"NAMED_USE_COMMANDBUTTON_ABILITY",t:240,p:["Unit","CommandButton","Use commandbutton ability"]},
  {i:"NAMED_USE_COMMANDBUTTON_ABILITY_ON_NAMED",t:198,p:["Unit","CommandButton","Use commandbutton ability on an object"]},
  {i:"NAMED_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT",t:199,p:["Unit","CommandButton","Use commandbutton ability at a waypoint"]},
  {i:"NAMED_USE_COMMANDBUTTON_ABILITY_USING_WAYPOINT_PATH",t:-1,p:["Unit","CommandButton","Use commandbutton ability following waypoint path"]},
  {i:"TEAM_USE_COMMANDBUTTON_ABILITY",t:241,p:["Team","CommandButton","Use commandbutton ability"]},
  {i:"TEAM_USE_COMMANDBUTTON_ABILITY_ON_NAMED",t:238,p:["Team","CommandButton","Use commandbutton ability on an object"]},
  {i:"TEAM_USE_COMMANDBUTTON_ABILITY_AT_WAYPOINT",t:239,p:["Team","CommandButton","Use commandbutton ability at a waypoint"]},
  {i:"MAP_SWITCH_BORDER",t:201,p:["Map","Modify","Change the active area of the map"]},
  {i:"RADAR_FORCE_ENABLE",t:208,p:["Radar","Control","Force enable the radar"]},
  {i:"SCREEN_SHAKE",t:210,p:["Camera","Shake Screen"]},
  {i:"TECHTREE_MODIFY_BUILDABILITY_OBJECT",t:211,p:["Map","Modify","Adjust the tech tree for a specific object type"]},
  {i:"WAREHOUSE_SET_VALUE",t:212,p:["Unit","Set cash value of Warehouse"]},
  {i:"SOUND_DISABLE_TYPE",t:217,p:["Multimedia","Sound Events","Sound Events -- disable type"]},
  {i:"SOUND_ENABLE_TYPE",t:218,p:["Multimedia","Sound Events","Sound Events -- enable type"]},
  {i:"SOUND_REMOVE_TYPE",t:321,p:["Multimedia","Sound Events","Sound Events -- remove type"]},
  {i:"SOUND_REMOVE_ALL_DISABLED",t:320,p:["Multimedia","Sound Events","Sound Events -- remove all disabled"]},
  {i:"SOUND_ENABLE_ALL",t:219,p:["Multimedia","Sound Events","Sound Events -- enable all"]},
  {i:"AUDIO_OVERRIDE_VOLUME_TYPE",t:220,p:["Multimedia","Sound Events","Sound Events -- override volume -- type"]},
  {i:"AUDIO_RESTORE_VOLUME_TYPE",t:221,p:["Multimedia","Sound Events","Sound Events -- restore volume -- type"]},
  {i:"AUDIO_RESTORE_VOLUME_ALL_TYPE",t:222,p:["Multimedia","Sound Events","Sound Events -- restore volume -- all"]},
  {i:"NAMED_SET_TOPPLE_DIRECTION",t:226,p:["Unit","Set topple direction"]},
  {i:"UNIT_MOVE_TOWARDS_NEAREST_OBJECT_TYPE",t:227,p:["Unit","Move","Move unit towards the nearest object of a specific type"]},
  {i:"TEAM_MOVE_TOWARDS_NEAREST_OBJECT_TYPE",t:228,p:["Team","Move","Move team towards the nearest object of a specific type"]},
  {i:"SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_ALL",t:259,p:["Skirmish","Delay a sequential script until the specified command ability is ready - all"]},
  {i:"SKIRMISH_WAIT_FOR_COMMANDBUTTON_AVAILABLE_PARTIAL",t:260,p:["Skirmish","Delay a sequential script until the specified command ability is ready - partial"]},
  {i:"TEAM_ALL_USE_COMMANDBUTTON_ON_NEAREST_OBJECTTYPE",t:268,p:["Team","CommandButton","Use command ability -- all -- nearest object type"]},
  {i:"TEAM_PARTIAL_USE_COMMANDBUTTON",t:269,p:["Team","CommandButton","Use command ability -- partial -- self"]},
  {i:"TEAM_CAPTURE_NEAREST_UNOWNED_FACTION_UNIT",t:270,p:["Team","Capture unowned faction unit -- nearest"]},
  {i:"TEAM_WAIT_FOR_NOT_CONTAINED_ALL",t:279,p:["Team","SequentialScript","Delay a sequential script until the team is no longer contained - all"]},
  {i:"OBJECTLIST_ADDOBJECTTYPE",t:287,p:["Scripting","ObjectTypeList","Add Object Type"]},
  {i:"OBJECTLIST_REMOVEOBJECTTYPE",t:288,p:["Scripting","ObjectTypeList","Remove Object Type"]},
  {i:"MAP_REVEAL_PERMANENTLY_AT_WAYPOINT",t:289,p:["Map","Shroud or Reveal","Reveal map at waypoint -- permanently"]},
  {i:"MAP_UNDO_REVEAL_PERMANENTLY_AT_WAYPOINT",t:290,p:["Map","Shroud or Reveal","Reveal map at waypoint -- undo permanently"]},
  {i:"EVA_SET_ENABLED_DISABLED",t:293,p:["Scripting","Enable or Disable EVA"]},
  {i:"OPTIONS_SET_OCCLUSION_MODE",t:294,p:["Scripting","Enable or Disable Occlusion (Drawing Behind Buildings)"]},
  {i:"OPTIONS_SET_DRAWICON_UI_MODE",t:296,p:["Scripting","Enable or Disable Draw-icon UI"]},
  {i:"OPTIONS_SET_PARTICLE_CAP_MODE",t:297,p:["Scripting","Enable or Disable Particle Cap"]},
  {i:"UNIT_AFFECT_OBJECT_PANEL_FLAGS",t:299,p:["Unit","Affect flags set on object panel"]},
  {i:"TEAM_AFFECT_OBJECT_PANEL_FLAGS",t:300,p:["Team","Affect flags set on object panel - all"]},
  {i:"PLAYER_SELECT_SKILLSET",t:301,p:["Player","Set","Set the skillset for a computer player"]},
  {i:"SCRIPTING_OVERRIDE_HULK_LIFETIME",t:302,p:["Scripting","Hulk set override lifetime"]},
  {i:"NAMED_FACE_NAMED",t:303,p:["Unit","Set unit to face another unit"]},
  {i:"NAMED_FACE_WAYPOINT",t:304,p:["Unit","Set unit to face a waypoint"]},
  {i:"TEAM_FACE_NAMED",t:305,p:["Team","Move","Set team to face another unit"]},
  {i:"TEAM_FACE_WAYPOINT",t:306,p:["Team","Move","Set team to face a waypoint"]},
  {i:"COMMANDBAR_REMOVE_BUTTON_OBJECTTYPE",t:307,p:["Scripting","Remove a command button from an object type"]},
  {i:"COMMANDBAR_ADD_BUTTON_OBJECTTYPE_SLOT",t:308,p:["Scripting","Add a command button to an object type"]},
  {i:"UNIT_SPAWN_NAMED_LOCATION_ORIENTATION",t:309,p:["Unit","Spawn","Spawn -- named unit on a team at a position with an orientation"]},
  {i:"PLAYER_AFFECT_RECEIVING_EXPERIENCE",t:310,p:["Player","Experience","Change the modifier to generals experience that a player receives"]},
  {i:"SOUND_SET_VOLUME",t:315,p:["Multimedia","Set the current sound volume"]},
  {i:"SPEECH_SET_VOLUME",t:316,p:["Multimedia","Set the current speech volume"]},
  {i:"OBJECT_ALLOW_BONUSES",t:319,p:["Map","Modify","Adjust Object Bonuses based on difficulty"]},
  {i:"TEAM_GUARD_IN_TUNNEL_NETWORK",t:322,p:["Team","Guard","Set to guard - from inside tunnel network"]},
  {i:"LOCALDEFEAT",t:295,p:["Multiplayer","Announce local defeat"]},
  {i:"RESIZE_VIEW_GUARDBAND",t:327,p:["Map","Modify","Resize view guardband"]},
  {i:"DELETE_ALL_UNMANNED",t:328,p:["Scripting","Delete all unmanned (sniped) vehicles"]},
  {i:"CHOOSE_VICTIM_ALWAYS_USES_NORMAL",t:329,p:["Map","Modify","Force ChooseVictim to ignore game difficulty and always use Normal setting"]}
];